from __future__ import annotations

from typing import Any

class Module:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

class Parameter: ...

class Linear(Module):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def __getattr__(name: str) -> Any: ...
