_wandb:
    value:
        cli_version: 0.23.1
        e:
            7jrffsj72nj8ww49xy5syynmaqq8l0y5:
                codePath: var/openr1/bin/pytest
                codePathLocal: var/openr1/bin/pytest
                cpu_count: 40
                cpu_count_logical: 80
                disk:
                    /:
                        total: "552866439168"
                        used: "27305361408"
                email: ogd3@georgetown.edu
                executable: /n/fs/similarity/maxent-grpo/var/openr1/bin/python
                git:
                    commit: c3ec7fc90b807125ce025816dad1502b5f010356
                    remote: git@github.com:liv-daliberti/maxent-grpo.git
                host: rinse.cs.princeton.edu
                memory:
                    total: "1081155600384"
                os: Linux-5.14.0-570.24.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /n/fs/similarity/maxent-grpo/var/openr1/bin/pytest
                python: CPython 3.11.14
                root: /n/fs/similarity/maxent-grpo
                startedAt: "2025-12-10T02:41:49.344682Z"
                writerId: 7jrffsj72nj8ww49xy5syynmaqq8l0y5
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 53
                - 71
                - 84
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 50
                - 53
                - 71
                - 84
                - 105
            "3":
                - 2
                - 13
                - 16
                - 24
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
run/config_path:
    value: null
run/git_sha:
    value: deadbeef
run/recipe_path:
    value: recipe.yaml
