from __future__ import annotations

from typing import Any, Iterator, Sequence

class Tensor:
    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: Any) -> Tensor: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __add__(self, other: Any) -> Tensor: ...
    def __radd__(self, other: Any) -> Tensor: ...
    def __sub__(self, other: Any) -> Tensor: ...
    def __rsub__(self, other: Any) -> Tensor: ...
    def __mul__(self, other: Any) -> Tensor: ...
    def __rmul__(self, other: Any) -> Tensor: ...
    def __truediv__(self, other: Any) -> Tensor: ...
    def __rtruediv__(self, other: Any) -> Tensor: ...
    def __matmul__(self, other: Any) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def detach(self) -> Tensor: ...
    def float(self) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def to(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def clamp(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def pow(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def sum(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def mean(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def std(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def min(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def max(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def numel(self) -> int: ...
    def item(self) -> Any: ...
    def view(self, *shape: Any) -> Tensor: ...
    def reshape(self, *shape: Any) -> Tensor: ...
    def flatten(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def transpose(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def unsqueeze(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def eq(self, other: Any) -> Tensor: ...
    def new_zeros(self, size: Any, *args: Any, **kwargs: Any) -> Tensor: ...
    def size(self, *args: Any, **kwargs: Any) -> Any: ...
    def tolist(self) -> list[Any]: ...
    @property
    def shape(self) -> Sequence[int]: ...

class device: ...
class dtype: ...

def __getattr__(name: str) -> Any: ...
