"""Prompt-only counterfactual proposals from model-discovered exemplars.

The intervention in this module is deliberately answer-blind beyond one
validator-confirmed response previously generated by the same policy.  It does
not expose an exhaustive catalogue, a desired support size, an entropy target,
or evaluation feedback.
"""

from __future__ import annotations

import json
from typing import Any


_ASSISTANT_MARKERS = (
    "<|im_start|>assistant\n",
    "\nAssistant: <think>",
)

_CHAT_CONTROL_MARKERS = (
    "<|im_start|>",
    "<|im_end|>",
    "<|endoftext|>",
)

_TASK_DIRECTIVES = {
    "python_factor": (
        "Construct a different lambda from scratch. Its returned divisor must "
        "differ for at least one listed input n; copying the same lambda or "
        "the same return vector is forbidden."
    ),
    "graph_coloring": (
        "Construct a different proper coloring from scratch. At least one "
        "vertex's color must change while every edge remains properly colored."
    ),
    "countdown": (
        "Construct a different arithmetic expression tree from scratch while "
        "still using every supplied number exactly once and reaching the target."
    ),
    "mathir": (
        "Construct a different valid algebraic operation sequence from scratch. "
        "Its executed intermediate equation-state trace must differ."
    ),
    "generic": (
        "Construct a semantically different executable solution from scratch; "
        "do not copy the prior final answer."
    ),
}

_ATTEMPT_DIRECTIVES = (
    "Privately identify the prior executable result, then make a concrete "
    "semantic mutation before writing the final answer.",
    "Do not edit or paraphrase the prior answer. Use an independent "
    "construction strategy and verify that its executable result changes.",
    "Restart the solution from the original problem constraints. Explicitly "
    "check privately that at least one executed state or output differs.",
)


def resolve_counterfactual_task_kind(reference: Any) -> str:
    """Map only the public executable-validator type to a fixed directive."""

    try:
        spec = json.loads(reference) if isinstance(reference, str) else reference
        if not isinstance(spec, dict):
            return "generic"
        verifier = str(spec.get("verifier", ""))
    except (TypeError, ValueError, json.JSONDecodeError):
        return "generic"
    if verifier == "python_factor_function":
        return "python_factor"
    if verifier == "graph_coloring":
        return "graph_coloring"
    if verifier == "countdown":
        return "countdown"
    if "mathir" in verifier:
        return "mathir"
    return "generic"


def _neutralize_chat_control_markers(text: str) -> str:
    """Prevent a decoded model response from opening or closing chat roles."""

    sanitized = str(text)
    for marker in _CHAT_CONTROL_MARKERS:
        sanitized = sanitized.replace(marker, marker.replace("<|", "< |"))
    return sanitized


def format_verified_counterfactual_prompt(
    prompt: str,
    verified_previous_answer: str,
    *,
    trailing_excerpt: bool = False,
    task_kind: str = "generic",
    attempt_index: int = 0,
) -> str:
    """Ask for a different executable outcome from one verified model answer.

    The caller obtains ``verified_previous_answer`` from the policy's current
    neutral group or validator-positive replay bank. The text is inserted
    inside the system role for Qwen prompts and immediately before the
    assistant marker for retained no-template paths.
    """

    if not isinstance(prompt, str) or not prompt:
        raise ValueError("counterfactual proposal prompt must be non-empty")
    if (
        not isinstance(verified_previous_answer, str)
        or not verified_previous_answer.strip()
    ):
        raise ValueError(
            "counterfactual proposal requires a non-empty verified answer"
        )
    if task_kind not in _TASK_DIRECTIVES:
        raise ValueError("unknown counterfactual proposal task kind")
    if isinstance(attempt_index, bool) or int(attempt_index) < 0:
        raise ValueError("counterfactual proposal attempt index must be nonnegative")
    answer = _neutralize_chat_control_markers(
        verified_previous_answer.strip()
    )
    excerpt_label = (
        "trailing excerpt of a validator-confirmed answer"
        if trailing_excerpt
        else "validator-confirmed answer"
    )
    intervention = (
        "Counterfactual proposal instruction: this same policy previously "
        f"produced the following {excerpt_label} for the current problem.\n"
        "<verified_previous_answer>\n"
        f"{answer}\n"
        "</verified_previous_answer>\n"
        "Produce a valid answer whose executable outcome is different from "
        "that prior answer. A merely reformatted equivalent is not different. "
        "The prior executable outcome is forbidden and will be rejected. "
        f"{_TASK_DIRECTIVES[task_kind]} "
        f"This is fixed-budget proposal attempt {int(attempt_index) + 1}. "
        f"{_ATTEMPT_DIRECTIVES[int(attempt_index) % len(_ATTEMPT_DIRECTIVES)]} "
        "Follow the original output format. Do not discuss the prior answer "
        "or this instruction."
    )

    qwen_system = "<|im_start|>system\n"
    if prompt.startswith(qwen_system):
        system_end = prompt.find("<|im_end|>", len(qwen_system))
        if system_end < 0:
            raise ValueError(
                "Qwen counterfactual prompt is missing its system terminator"
            )
        return (
            prompt[:system_end].rstrip()
            + "\n"
            + intervention
            + prompt[system_end:]
        )
    for marker in _ASSISTANT_MARKERS:
        if prompt.endswith(marker):
            return prompt[: -len(marker)] + intervention + "\n" + marker
    return prompt.rstrip() + "\n" + intervention + "\n"
