from typing import Any, ContextManager

class Accelerator:
    num_processes: int
    process_index: int
    is_main_process: bool
    device: Any
    state: Any
    sync_gradients: bool

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def prepare(self, *args: Any, **kwargs: Any) -> Any: ...
    def backward(self, loss: Any, *args: Any, **kwargs: Any) -> None: ...
    def accumulate(self, model: Any) -> ContextManager[Any]: ...
    def gather(self, data: Any, *args: Any, **kwargs: Any) -> Any: ...
    def gather_object(self, obj: Any, *args: Any, **kwargs: Any) -> Any: ...
    def broadcast_object_list(self, obj_list: Any, *args: Any, **kwargs: Any) -> None: ...
    def scatter_object(self, obj_list: Any, *args: Any, **kwargs: Any) -> Any: ...
    def unwrap_model(self, model: Any) -> Any: ...
    def wait_for_everyone(self) -> None: ...
    def save_state(self, *args: Any, **kwargs: Any) -> None: ...
    def load_state(self, *args: Any, **kwargs: Any) -> None: ...
