from __future__ import annotations

from typing import Any

class Optimizer:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def step(self, *args: Any, **kwargs: Any) -> Any: ...
    def zero_grad(self, *args: Any, **kwargs: Any) -> Any: ...

class AdamW(Optimizer): ...

def __getattr__(name: str) -> Any: ...
