#!/usr/bin/env python3
"""Render every registered conditional-concentration contrast into appendix tables."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from paper_domain_typography import format_domain_names
import argparse
import json

ROOT = Path(__file__).resolve().parents[2]
# Default to the data and tables included by the current manuscript.
SOURCE = ROOT / 'paper/results/conditional_concentration_20260912.json'
TARGET = ROOT / 'paper/results/conditional_concentration_20260912_tables.tex'
DOMAINS = {'graph_coloring':'Graph','countdown':'Countdown','python_factors':'Python','mathir':'MathIR','pantry_plan':'PantryPlan'}
METHODS = {'drgrpo':'Dr.GRPO','grpo':'GRPO','maxrl':'MaxRL','replay_drgrpo':'Re:Dr','replay_maxrl':'Re:Max'}
SCALES = {'qwen05b':'Qwen2.5-0.5B','falcon1b':'Falcon3-1B','qwen3b':'Qwen2.5-3B'}

def number(v):
    return '--' if v is None else f'{v:+.3f}'

def render(record):
    out = ['% Generated by ops/exp_scaling/build_paper_conditional_concentration_appendix.py.']
    for kind in ('before_after','replay_effect'):
        for level in ('level1','level2'):
            for scale, model in SCALES.items():
                blocks = [b for b in record['blocks'] if (b['kind'],b['level'],b['scale']) == (kind,level,scale)]
                if not blocks:
                    continue
                replay = kind != 'before_after'
                comparison = 'Replay and conditional concentration' if replay else 'Initial-to-final conditional concentration'
                column = 'Control' if replay else 'Objective'
                legend = (
                    r'Each row gives Re:Dr minus Dr.GRPO or Re:Max minus MaxRL at step 3,072; '
                    r'negative $\Delta\widehat C$ means lower concentration among correct outputs.'
                    if replay else
                    r'Each row compares the same method at initialization and step 3,072; '
                    r'positive $\Delta\widehat C$ means greater concentration among correct outputs.'
                )
                out += [r'\begin{table}[!htbp]',r'\centering',r'\scriptsize',r'\setlength{\tabcolsep}{3pt}',
                    r'\begin{tabular}{@{}llcrlrrr@{}}',r'\toprule',
                    f'Domain & {column} & $n$ & ' + r'$\Delta\widehat C$ & nominal 95\% interval & $|E_s|$ & split 0 ($n$) & split 1 ($n$) \\',r'\midrule']
                for b in blocks:
                    s=b['summaries'];v=s['distinct_streams'];ci=v['ci95']
                    interval='--' if ci is None else f'[{ci[0]:+.3f}, {ci[1]:+.3f}]'
                    counts=list(v['eligible_counts'].values())
                    coverage='--' if not counts else (str(min(counts)) if min(counts)==max(counts) else f'{min(counts)}--{max(counts)}')
                    split=[f"{number(s[x]['mean'])} ({s[x]['n']})" for x in ('orientation0','orientation1')]
                    out.append(f"{DOMAINS[b['domain']]} & {METHODS[b['method']]} & {v['n']} & {number(v['mean'])} & {interval} & {coverage} & {split[0]} & {split[1]} " + r'\\')
                out += [r'\bottomrule',r'\end{tabular}',
                    f"\\caption{{\\textbf{{{comparison}: {model}, Level {level[-1]}.}} {legend} "
                    r'$n$ counts seeds with defined estimates; $|E_s|$ gives the range of eligible prompt counts. '
                    r'Splits 0 and 1 reverse the assignment of disjoint stream identifiers, with eligibility determined separately. '
                    r'Nominal 95\% Student-$t$ intervals require five defined seed estimates.}',r'\end{table}','']
    return format_domain_names('\n'.join(out))

if __name__=='__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=SOURCE)
    parser.add_argument('--target', type=Path, default=TARGET)
    args = parser.parse_args()
    args.target.write_text(render(json.loads(args.source.read_text()))+'\n')
    print(json.dumps({'event': 'built', 'source': str(args.source),
                      'target': str(args.target)}))
