#!/usr/bin/env python3
"""Emit the B3a appendix table body from the frozen summary artifact.

Transcribing five-seed means into LaTeX by hand is exactly how a paper acquires
a number that no longer matches its data. This renders the rows instead, and
marks any domain the protocol withholds so a partially complete cohort is
visibly partial in the manuscript rather than silently short a row.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DOMAIN_ORDER = (
    ("graph_coloring", "Graph coloring"),
    ("countdown", "Countdown"),
    ("python_factors", "Python factors"),
    ("mathir", "MathIR action menu"),
    ("pantry_plan", "PantryPlan"),
)


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def fmt(value: float | None, places: int = 3) -> str:
    if value is None:
        return "--"
    text = f"{value:.{places}f}"
    # Match the manuscript's leading-zero-free style for bounded quantities.
    return text[1:] if text.startswith("0.") else text


def signed(value: float | None) -> str:
    if value is None:
        return "--"
    body = fmt(abs(value))
    return f"$-${body}" if value < 0 else f"$+${body}"


def render_rows(summary: dict[str, Any]) -> tuple[str, list[str]]:
    by_domain = {entry["domain"]: entry for entry in summary["domains"]}
    lines: list[str] = []
    pending: list[str] = []
    for key, title in DOMAIN_ORDER:
        entry = by_domain.get(key)
        if entry is None or not entry.get("reportable"):
            seeds = len(entry.get("terminal_seeds", [])) if entry else 0
            pending.append(title)
            lines.append(
                f"    {title:<18} & \\multicolumn{{5}}{{c}}"
                f"{{\\emph{{pending: {seeds}/5 seeds terminal}}}} \\\\"
            )
            continue
        means = entry["means"]
        paired = entry["paired"]
        lines.append(
            f"    {title:<18} & {fmt(means['drgrpo']['distinct8']):>6} "
            f"& {fmt(means['b3a']['distinct8']):>6} "
            f"& {fmt(means['xgrpo']['distinct8']):>6} "
            f"& {signed(paired['b3a_minus_xgrpo_distinct8']['mean']):>12} "
            f"& {signed(paired['b3a_minus_drgrpo_distinct8']['mean']):>12} \\\\"
        )
    return "\n".join(lines), pending


def main() -> int:
    root = repo_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--summary",
        type=Path,
        default=root / "var" / "artifacts" / "e72_b3a_summary.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / "paper" / "figures" / "e72_b3a_table_body.tex",
    )
    args = parser.parse_args()

    summary = json.loads(args.summary.read_text())
    body, pending = render_rows(summary)
    # The complete tabular is emitted, not just its rows: \input cannot begin a
    # row inside an alignment, so a rows-only fragment makes \bottomrule a
    # misplaced \noalign. Inputting a self-contained tabular avoids that.
    document = "\n".join(
        [
            "% Generated by ops/exp_scaling/render_e72_b3a_table.py from",
            "% var/artifacts/e72_b3a_summary.json. Do not edit by hand.",
            r"\begin{tabular}{@{}lrrrrr@{}}",
            r"  \toprule",
            r"  & \multicolumn{3}{c}{\textbf{\#modes} (\texttt{distinct@8})} &",
            r"  \multicolumn{2}{c}{\textbf{paired difference}} \\",
            r"  \cmidrule(lr){2-4}\cmidrule(lr){5-6}",
            r"  \textbf{Domain} & matched Dr.GRPO & B3a & \xdr{} &",
            r"  B3a $-$ \xdr{} & B3a $-$ Dr.GRPO \\",
            r"  \midrule",
            body,
            r"  \bottomrule",
            r"\end{tabular}",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(document + "\n", encoding="utf-8")

    reportable = len(DOMAIN_ORDER) - len(pending)
    print(f"[e72-b3a-table] wrote {args.output} ({reportable}/{len(DOMAIN_ORDER)} domains)")
    if pending:
        print(f"[e72-b3a-table] pending: {', '.join(pending)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
