# Copyright 2025 Liv d'Aliberti
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

"""Compatibility facade for scoring helpers.

Implementation is split across focused modules:
- ``scoring_batching`` (prompt/completion batching + slices)
- ``scoring_logprob`` (policy/reference logprob kernels + sequence scores)
- ``scoring_reference`` (reference-model/vLLM metadata paths)
"""

from __future__ import annotations

from .scoring_common import (  # noqa: F401
    _SCORING_EXCEPTIONS,
    _as_context_manager,
    _autocast_context,
    _coerce_optional_int,
    _dist_all,
    _dist_any,
    _dist_collective_ready,
    _get_config_value,
    _get_embedding_vocab_size,
    _LongDTypeProxy,
    _model_has_non2d_embeddings,
    _PadTokenGuard,
    _prefetch_iterator,
    _progress_log_enabled,
    _refresh_torch,
    _resolve_dtype,
    _score_slice_log_enabled,
    _to_numpy_array,
    _TorchModuleLike,
    _weight_is_stub_tensor,
    _weight_is_two_dimensional,
    _describe_embedding_module,
)
from .scoring_batching import (  # noqa: F401
    CompletionTensors,
    _PromptCacheConfig,
    _SliceState,
    _apply_eos_completion_mask,
    _collect_prompt_entries,
    _completion_tensors_from_token_ids,
    _prepare_prompt_slice,
    _slice_tail_window,
    _tokenize_completions,
    build_score_batch,
    iter_batch_slices,
    iter_batch_slices_trl,
    summarize_completion_lengths,
    token_counts_from_score_batch,
)
from .scoring_logprob import (  # noqa: F401
    _as_torch_tensor,
    _chunked_sequence_logprobs,
    _match_tensor_length,
    _summon_fsdp_full_param_context,
    _trl_get_per_token_logps,
    build_sequence_scores,
    score_model_outputs,
    selective_log_softmax,
)
from .scoring_reference import (  # noqa: F401
    _coerce_int_optional,
    _coerce_logprob_value,
    _meta_field,
    _sum_token_logprobs,
    finalize_reference_stats,
    gather_reference_logprobs,
    reference_from_model,
    reference_from_model_trl,
    reference_from_vllm_meta,
    reference_stats_from_policy_logprobs,
    vllm_meta_has_logprobs,
)

__all__ = [
    "CompletionTensors",
    "_PromptCacheConfig",
    "_SliceState",
    "_SCORING_EXCEPTIONS",
    "_LongDTypeProxy",
    "_PadTokenGuard",
    "_TorchModuleLike",
    "_apply_eos_completion_mask",
    "_as_context_manager",
    "_as_torch_tensor",
    "_autocast_context",
    "_chunked_sequence_logprobs",
    "_coerce_int_optional",
    "_coerce_logprob_value",
    "_coerce_optional_int",
    "_collect_prompt_entries",
    "_completion_tensors_from_token_ids",
    "_describe_embedding_module",
    "_dist_all",
    "_dist_any",
    "_dist_collective_ready",
    "_get_config_value",
    "_get_embedding_vocab_size",
    "_match_tensor_length",
    "_meta_field",
    "_model_has_non2d_embeddings",
    "_prepare_prompt_slice",
    "_prefetch_iterator",
    "_progress_log_enabled",
    "_refresh_torch",
    "_resolve_dtype",
    "_score_slice_log_enabled",
    "_slice_tail_window",
    "_sum_token_logprobs",
    "_summon_fsdp_full_param_context",
    "_to_numpy_array",
    "_tokenize_completions",
    "_trl_get_per_token_logps",
    "_weight_is_stub_tensor",
    "_weight_is_two_dimensional",
    "build_score_batch",
    "build_sequence_scores",
    "finalize_reference_stats",
    "gather_reference_logprobs",
    "iter_batch_slices",
    "iter_batch_slices_trl",
    "reference_from_model",
    "reference_from_model_trl",
    "reference_from_vllm_meta",
    "reference_stats_from_policy_logprobs",
    "score_model_outputs",
    "selective_log_softmax",
    "summarize_completion_lengths",
    "token_counts_from_score_batch",
    "vllm_meta_has_logprobs",
]
