from typing import Any, Iterable, Optional


class GatheredParameters:
    def __init__(self, params: Iterable[Any], modifier_rank: Optional[int] = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool | None: ...


def is_enabled() -> bool: ...
