command: train-maxent
maxent:
  recipe: configs/recipes/Qwen2.5-1.5B-Instruct/grpo/config_math.yaml
  training:
    objective: grpo
    controller_meta_enabled: false
    num_generations: 2
    output_dir: var/data/Qwen2.5-1.5B-Open-R1-GRPO-BASELINE-math-v1

hydra:
  run:
    dir: var/artifacts/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: var/artifacts/outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
