from typing import Any, Dict, Optional

class ModelConfig:
    model_name_or_path: str
    model_revision: str | None
    trust_remote_code: bool
    attn_implementation: str | None
    torch_dtype: Any

    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class ScriptArguments:
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class GRPOConfig:
    def __init__(self, **kwargs: Any) -> None: ...
    def get_process_log_level(self) -> int: ...
    def __getattr__(self, name: str) -> Any: ...


class GRPOTrainer:
    accelerator: Any
    model: Any

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def train(self, *args: Any, **kwargs: Any) -> Any: ...
    def evaluate(self, *args: Any, **kwargs: Any) -> Any: ...
    def save_state(self) -> None: ...
    def save_model(self, *args: Any, **kwargs: Any) -> None: ...
    def log_metrics(self, *args: Any, **kwargs: Any) -> None: ...
    def save_metrics(self, *args: Any, **kwargs: Any) -> None: ...
    def create_model_card(self, *args: Any, **kwargs: Any) -> None: ...
    def push_to_hub(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class TrlParser:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def parse_args_and_config(self) -> tuple[Any, Any, Any]: ...


def get_kbit_device_map(*args: Any, **kwargs: Any) -> Optional[Dict[str, Any]]: ...

def get_quantization_config(*args: Any, **kwargs: Any) -> Optional[Any]: ...

def get_peft_config(*args: Any, **kwargs: Any) -> Any: ...
