from typing import Any

class VLLMClient:
    def __init__(self, base_url: str | None = ...) -> None: ...
    def init_communicator(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
