from typing import Any, Mapping, Sequence


class Pipeline:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def run(self, *args: Any, **kwargs: Any) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_dict(self) -> Mapping[str, Any]: ...
    def __iter__(self) -> Sequence[Any]: ...
