#!/usr/bin/env python3
"""Render the two-wording GPT-5.6 Sol Python condition into its appendix.

Every number below is read from the frozen paired analysis; none is retyped.
The condition qualifies the one substituted cell in the hosted display, and
replaces no published cell, so it is rendered as its own subsection rather than
folded into any cohort table.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

try:
    from ops.paper_domain_typography import format_domain_names
except ModuleNotFoundError:
    from paper_domain_typography import format_domain_names

_DOMAIN_LANGUAGE_EXCEPTIONS = (
    "Python lambda", r"Python \texttt{lambda}", "Python modulo",
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = (ROOT / 'artifacts/frontier_modebench_gpt56sol_python_parity_20260918'
                  / 'paired_wording_comparison.json')
DEFAULT_OUTPUT = ROOT / 'paper/results/gpt56sol_python_parity_20260918'
ARMS = ('original', 'revised')
LEVELS = (1, 2, 3)
#: The support bar the rest of the paper applies to every PCMD cell.
MIN_DEFINED_PROMPTS = 30
ARM_LABELS = {'original': 'Original', 'revised': 'Revised, no system'}


def file_sha(path: Path) -> str:
    with Path(path).open('rb') as handle:
        digest = hashlib.sha256()
        for chunk in iter(lambda: handle.read(1024 * 1024), b''):
            digest.update(chunk)
    return digest.hexdigest()


def require(condition, message: str) -> None:
    if not condition:
        raise ValueError(message)


WORDS = ('none', 'one', 'two', 'three', 'four', 'five')


def _cells_phrase(reportable: int, total: int) -> str:
    """Small counts are words in this paper, and this one is usually zero."""
    if reportable == 0:
        return f'none of its {WORDS[total]} cells'
    return f'{WORDS[reportable]} of its {WORDS[total]} cells'


def _three(value: float | None) -> str:
    if value is None:
        return '---'
    text = f'{value:.3f}'
    return text[1:] if text.startswith('0.') else text


def _signed(value: float | None) -> str:
    if value is None:
        return '---'
    return ('$+' if value >= 0 else '$-') + _three(abs(value)) + '$'


def _interval(entry: dict) -> str:
    if entry.get('ci95') is None:
        return '---'
    low, high = entry['ci95']
    # Signed bounds are set in math mode so the minus signs are minus signs.
    return f'$[{_signed(low)[1:-1]}, {_signed(high)[1:-1]}]$'


def load(source: Path) -> dict:
    record = json.loads(Path(source).read_text(encoding='utf-8'))
    require(record.get('schema') == 'gpt56sol-python-wording-parity-analysis-v1',
            'Unexpected paired-analysis schema')
    require(tuple(record['population']['arms']) == ARMS, 'The compared arms changed')
    require(record['deployment']['build_equality_with_published_cells'] == 'not established',
            'This condition may not assert build equality with the published cells')
    return record


def build_record(source: Path = DEFAULT_SOURCE) -> dict[str, Any]:
    record = load(source)
    cells = record['cells']
    refusals = record['native_refusals']
    total_refusals = sum(refusals.values())
    buckets = record['surface_taxonomy']['buckets']
    marker_cells = {arm: buckets[f'{arm}/unscoreable_surface'] for arm in ARMS}
    parseable = {arm: buckets[f'{arm}/parseable_surface'] for arm in ARMS}
    require(all(bucket['verified'] == 0 for bucket in marker_cells.values()),
            'The unscoreable surface no longer explains a uniform grading failure')
    return {
        'schema': 'paper-gpt56sol-python-parity-v1',
        'source': {'path': str(Path(source).resolve().relative_to(ROOT)),
                   'sha256': file_sha(source)},
        'renderer': {'path': str(Path(__file__).resolve().relative_to(ROOT)),
                     'sha256': file_sha(Path(__file__))},
        'analysis': record,
        'headline': {
            'native_refusals_total': total_refusals,
            'unscoreable_rate': {arm: marker_cells[arm]['responses']
                                 / (marker_cells[arm]['responses'] + parseable[arm]['responses'])
                                 for arm in ARMS},
            'parseable_rate': {arm: parseable[arm]['rate'] for arm in ARMS},
            'reportable_revised_cells': sum(
                1 for level in LEVELS
                if cells[f'normalized/revised/level{level}']['collision_eligible_prompts']
                >= MIN_DEFINED_PROMPTS),
        },
    }


def render(record: dict[str, Any]) -> str:
    analysis = record['analysis']
    cells = analysis['cells']
    refusals = analysis['native_refusals']
    head = record['headline']
    buckets = analysis['surface_taxonomy']['buckets']
    lines = [
        '% Generated by ops/build_paper_gpt56sol_python_parity.py; do not edit.',
        r'\subsection{The revised Python wording on a second deployment}',
        r'\label{app:python-wording-second-deployment}',
        '',
        r'The original and revised Python conditions of App.~\ref{app:hosted-python-prompt}',
        r'are evaluated on GPT-5.6 Sol through \path{api.openai.com}. Each condition uses',
        r'the same 384 problems, with 128 prompts per level and eight responses per prompt,',
        r'medium reasoning effort and an 8,192-token output cap. The original condition',
        r'uses the benchmark request; the revised condition asks for a direct expression',
        r'without a system message. Public task inputs, allowed operators and the verifier',
        r'are unchanged, but wording and system-message presence change together.',
        r'Every response reports the model \texttt{gpt-5.6-sol}, but this build cannot be',
        r'shown to match the Azure deployment used for the hosted averages, so the two',
        r'are treated as separate populations.',
        '',
        r'\paragraph{Verified success and mode counts decrease under the revised condition.}',
        f'There are {"no" if not head["native_refusals_total"] else head["native_refusals_total"]} provider-declared refusals among the',
        f'{sum(cells[f"normalized/{arm}/level{level}"]["responses"] for arm in ARMS for level in LEVELS):,} responses in this comparison.',
        r'The Azure GPT-5.6 Sol cohort also contains no provider-declared refusals;',
        r'its missing strict Python diversity entries reflect too few verified draws.',
        r'Under normalized grading, the revised condition lowers accuracy and mean',
        r'\texttt{distinct@8} at each level (Table~\ref{tab:gpt56sol-python-parity}).',
        r'Revised-minus-original differences use all 128 prompts per level, pairing',
        r'problems across conditions and resampling whole eight-response groups:',
        rf'{analysis["bootstrap"]["replicates"]:,} replicates give pointwise 95\% percentile intervals.',
        r'Accuracy differences are fractions of responses; mode-count differences are',
        r'modes per prompt:',
    ]
    for metric, name in (('accuracy', 'accuracy'), ('distinct8', r'\texttt{distinct@8}')):
        values = [analysis['differences'][f'normalized/level{level}']['all_prompts'][metric]
                  for level in LEVELS]
        lines.append(f'{name} ' + ', '.join(
            f'{_signed(v["estimate"])} {_interval(v)}' for v in values)
            + (' at Levels 1--3;' if metric == 'accuracy' else ' respectively.'))
    lines.extend([
        r'The revised normalized cells have',
        ', '.join(str(cells[f'normalized/revised/level{level}']['collision_eligible_prompts'])
                  for level in LEVELS),
        rf'prompts with at least two verified responses, all below the {MIN_DEFINED_PROMPTS}-prompt',
        r'reporting threshold, so their success-conditional diversity and any diversity',
        r'contrast are omitted.',
        '',
        r'\paragraph{Formatting failures accompany the lower scores.}',
        r'The literal \LaTeX{} marker \verb|\text{| appears in',
        rf'{buckets["original/unscoreable_surface"]["responses"]:,} original-condition and',
        rf'{buckets["revised/unscoreable_surface"]["responses"]:,} revised-condition responses',
        rf'({100 * head["unscoreable_rate"]["original"]:.0f}\% and {100 * head["unscoreable_rate"]["revised"]:.0f}\%).',
        r'The formatting normalizer does not remove this wrapper; none of these responses',
        r'verifies. Among responses without the marker, normalized success is',
        rf'{100 * head["parseable_rate"]["original"]:.1f}\% and {100 * head["parseable_rate"]["revised"]:.1f}\%, respectively.',
        r'Absence of this marker does not guarantee parseability. Because the marker',
        r'depends on the response, these subsets are not matched comparisons and do not',
        r'bound a content or capability effect.',
        '',
        r'\paragraph{Prompt-interface sensitivity differs across deployments.}',
        r'The revised condition increases normalized success and verified mode counts',
        r'for Opus 5 (App.~\ref{app:hosted-python-prompt}) but decreases both for this',
        r'GPT-5.6 Sol deployment. This comparison does not isolate task wording from the',
        r'system message, establish that either task is generally easier, or identify',
        r'the effect on the remaining hosted deployments. The four-domain comparison in',
        r'Table~\ref{tab:hosted-level-averages-parity} holds the task prompts fixed across',
        r'all seven deployments by excluding Python.',
        '',
        r'\begin{table}[!htbp]',
        r'  \centering',
        r'  \caption{\textbf{The revised Python condition lowers normalized success and verified mode counts on GPT-5.6 Sol.}',
        r'  Both conditions use the same 128 problems per level and eight responses per',
        r'  prompt through \texttt{api.openai.com}, with medium reasoning effort and an',
        r'  8,192-token output cap. R counts provider-declared refusals; A is response',
        r'  accuracy (\%); D is mean \texttt{distinct@8} over all prompts.',
        r'  $1-C$ is pair-pooled diversity: the fraction of correct pairs with different',
        r'  solution modes, weighting each correct pair equally across prompts.',
        rf'  Dashes mark cells with fewer than {MIN_DEFINED_PROMPTS} prompts containing at least two',
        r'  verified draws. Strict grading uses the original output; normalized grading',
        r'  applies the same typography rules to both conditions. Entries are point',
        r'  estimates; paired uncertainty for accuracy and mode-count differences is',
        r'  given in the surrounding text.}',
        r'  \small',
        r'  \setlength{\tabcolsep}{4pt}',
        r'  \begin{tabular}{@{}llrrrrrrr@{}}',
        r'    \toprule',
        r'    & & & \multicolumn{3}{c}{Strict} & \multicolumn{3}{c}{Normalized} \\',
        r'    \cmidrule(lr){4-6}\cmidrule(lr){7-9}',
        r'    Wording & L & R & A & D & $1-C$ & A & D & $1-C$ \\',
        r'    \midrule',
    ])
    for index, arm in enumerate(ARMS):
        if index:
            lines.append(r'    \midrule')
        for level in LEVELS:
            columns = [ARM_LABELS[arm] if level == LEVELS[0] else '', str(level),
                       str(refusals[f'{arm}/level{level}'])]
            for grading in ('strict', 'normalized'):
                cell = cells[f'{grading}/{arm}/level{level}']
                reportable = cell['collision_eligible_prompts'] >= MIN_DEFINED_PROMPTS
                columns.extend((f'{100 * cell["accuracy"]:.1f}', f'{cell["distinct8"]:.2f}',
                                _three(cell['pcmd']) if reportable else '---'))
            lines.append('    ' + ' & '.join(columns) + r' \\')
    lines.extend([
        r'    \bottomrule',
        r'  \end{tabular}',
        r'  \label{tab:gpt56sol-python-parity}',
        r'\end{table}',
    ])
    return format_domain_names('\n'.join(lines) + '\n', exclude_phrases=_DOMAIN_LANGUAGE_EXCEPTIONS)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=DEFAULT_SOURCE)
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    record = build_record(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.with_suffix('.json').write_text(
        json.dumps(record, indent=2, ensure_ascii=False, allow_nan=False) + '\n', encoding='utf-8')
    args.output.with_suffix('.tex').write_text(render(record), encoding='utf-8')
    print(f"Wrote {args.output.with_suffix('.tex')} and {args.output.with_suffix('.json')}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
