#!/usr/bin/env python3
"""Valid-mode counts for App. B's domain table, read from the frozen splits.

Table 4 quotes a mean number of correct execution modes per prompt, and B.1
quotes ranges beside it. Those were written by hand, and they were drawn from
two different populations without saying so: the means describe the evaluation
split, the ranges the training split. Both are recoverable exactly -- every
released row carries ``answer_mode_count`` -- so they are computed here and
expanded at compile time, each labelled with the split it came from.

The counts are properties of a frozen release and should not move. If one does,
the release changed, and the manuscript should say so rather than silently
print the new number under the old claim.
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_TEX = ROOT / "paper/results/domain_support_macros.tex"
OUT_JSON = ROOT / "paper/results/domain_support.json"

# Level 1, the construction every training comparison starts from. Paths match
# the dataset roots App. C prints beside each prompt.
DOMAINS = (
    ("Graph", "graph_coloring_modebench_v2"),
    ("Countdown", "exact_countdown_easy3_probe"),
    ("Python", "python_factor_modebench_v1"),
    ("MathIR", "mathir_action_menu_v1"),
    ("Pantry", "pantry_plan_modebench_v2"),
)
SPLITS = ("train", "eval")


def counts(root: Path, split: str) -> list[int]:
    from datasets import load_from_disk

    loaded = load_from_disk(str(root / split))
    if hasattr(loaded, "keys"):
        name = "multi_answer" if "multi_answer" in loaded else list(loaded.keys())[0]
        loaded = loaded[name]
    return list(loaded["answer_mode_count"])


def group(values: list[int]) -> dict:
    return {"rows": len(values), "mean": statistics.mean(values),
            "min": min(values), "max": max(values)}


def tex_int(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def main() -> None:
    record, lines = {}, [
        "% Generated by ops/build_paper_domain_support_macros.py; do not hand edit.",
    ]
    for label, stem in DOMAINS:
        root = ROOT / "var/data" / stem
        record[label] = {"dataset": f"var/data/{stem}"}
        for split in SPLITS:
            stats = group(counts(root, split))
            record[label][split] = stats
            tag = "" if split == "eval" else "Train"
            lines.append(
                r"\newcommand{\MDvm%s%s}{%.2f}" % (label, tag + "Mean", stats["mean"]))
            lines.append(
                r"\newcommand{\MDvm%s%sLo}{%s}" % (label, tag, tex_int(stats["min"])))
            lines.append(
                r"\newcommand{\MDvm%s%sHi}{%s}" % (label, tag, tex_int(stats["max"])))
            # A degenerate range reads as an error on the page ("5--5"), so it
            # collapses to the single value it actually is.
            span = (tex_int(stats["min"]) if stats["min"] == stats["max"]
                    else "%s--%s" % (tex_int(stats["min"]), tex_int(stats["max"])))
            lines.append(
                r"\newcommand{\MDvm%s%sRange}{%s}" % (label, tag, span))
    # B.2 states the Python specification format; the released instantiation is
    # narrower than the format allows, and the manuscript needs both.
    import json as _json
    cases, lows, highs = set(), [], []
    for split in SPLITS:
        from datasets import load_from_disk
        loaded = load_from_disk(str(ROOT / "var/data/python_factor_modebench_v1" / split))
        if hasattr(loaded, "keys"):
            loaded = loaded[list(loaded.keys())[0]]
        for raw in loaded["answer"]:
            values = _json.loads(raw)["cases"]
            cases.add(len(values))
            lows.append(min(values))
            highs.append(max(values))
    record["PythonCases"] = {"cases_per_prompt": sorted(cases),
                             "integer_range": [min(lows), max(highs)]}
    lines.append(r"\newcommand{\MDpyCases}{%s}" % ("".join(
        str(c) for c in sorted(cases)) if len(cases) == 1
        else "%d--%d" % (min(cases), max(cases))))
    lines.append(r"\newcommand{\MDpyCaseLo}{%d}" % min(lows))
    lines.append(r"\newcommand{\MDpyCaseHi}{%d}" % max(highs))
    OUT_TEX.write_text("\n".join(lines) + "\n")
    OUT_JSON.write_text(json.dumps(
        {"schema": "paper-domain-support-v1",
         "what": "valid-mode counts per prompt, per split, for the Level-1 "
                 "released datasets; the manuscript's means are the evaluation "
                 "split and its ranges the training split.",
         "builder": "ops/build_paper_domain_support_macros.py",
         "domains": record}, indent=1) + "\n")
    print(json.dumps({"event": "built", "macros": str(OUT_TEX),
                      "domains": len(record)}))


if __name__ == "__main__":
    main()
