#!/usr/bin/env python3
"""What MathIR contributes to the five-domain means, and which way it moves them.

MathIR keys a mode by its derivation rather than its answer, so its breadth
barely moves anywhere in the paper. That invites a reader to ask whether the
five-domain averages are carried by the four answer-keyed domains, and whether
retaining a near-flat domain flatters them. The second question has a
measurable answer and it is the opposite of the worry: MathIR sits below every
other domain's gain, so every five-domain mean is *lower* than the four-domain
mean over the same cells. This script measures both, so the appendix can quote
the direction and the size rather than assert them.

Its sources are the retention matrix the breadth figures already read and the
training record behind them; it computes nothing new, it only aggregates.
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATRIX = ROOT / 'paper/results/mode_diversity_retention_matrix.json'
TRAINING = ROOT / 'paper/results/mode_diversity_training.json'
MACROS = ROOT / 'paper/results/mathir_scope_macros.tex'
DOMAINS = ('graph_coloring', 'countdown', 'python_factors', 'mathir', 'pantry_plan')
HEADLINE = ('qwen05b', 'Re:Dr')


def _three(value: float) -> str:
    """A signed three-decimal figure written the way the paper writes PCMD."""
    return f'{value:+.3f}'.replace('0.', '.')


def cell_means(matrix: dict) -> list[dict]:
    """Five-domain and four-domain means for every cell carrying all five."""
    out = []
    for scale, arms in matrix['panel_a'].items():
        for arm, domains in arms.items():
            values = {d: (domains.get(d) or {}).get('mean') for d in DOMAINS}
            if any(v is None for v in values.values()):
                continue
            five = statistics.fmean(values.values())
            four = statistics.fmean(v for d, v in values.items() if d != 'mathir')
            out.append({'scale': scale, 'arm': arm, 'five': five, 'four': four,
                        'mathir': values['mathir'], 'shift': four - five})
    return out


def mathir_level(training: dict) -> dict:
    """MathIR's own terminal breadth, averaged over the arms that report it."""
    rows = [a for a in training['arms']
            if a['domain'] == 'mathir' and a.get('pmd_after') is not None]
    return {'pmd': statistics.fmean(a['pmd_after'] for a in rows),
            'neff': statistics.fmean(a['effective_modes_after'] for a in rows
                                     if a.get('effective_modes_after') is not None),
            'arms': len(rows)}


def macros(cells: list[dict], level: dict) -> str:
    head = next((c for c in cells if (c['scale'], c['arm']) == HEADLINE), None)
    if head is None:
        raise SystemExit(f'no complete five-domain cell for {HEADLINE}')
    shifts = [c['shift'] for c in cells]
    # Every cell must move the same way for the appendix sentence to be true.
    if min(shifts) <= 0:
        raise SystemExit('a five-domain mean is not below its four-domain mean; '
                         'the appendix claim no longer holds')
    lines = [
        '% Generated by ops/build_paper_mathir_scope_macros.py; do not hand edit.',
        fr'\newcommand{{\MIRpmdafter}}{{{level["pmd"]:.3f}'.replace('0.', '.') + '}',
        fr'\newcommand{{\MIRneffafter}}{{{level["neff"]:.2f}}}',
        fr'\newcommand{{\MIRfive}}{{{_three(head["five"])}}}',
        fr'\newcommand{{\MIRfour}}{{{_three(head["four"])}}}',
        fr'\newcommand{{\MIRshift}}{{{_three(head["shift"]).lstrip("+")}}}',
        fr'\newcommand{{\MIRshiftmin}}{{{_three(min(shifts)).lstrip("+")}}}',
        fr'\newcommand{{\MIRshiftmax}}{{{_three(max(shifts)).lstrip("+")}}}',
        fr'\newcommand{{\MIRshiftcells}}{{{len(cells)}}}',
    ]
    return '\n'.join(lines) + '\n'


def main() -> None:
    matrix = json.loads(MATRIX.read_text())
    training = json.loads(TRAINING.read_text())
    cells = cell_means(matrix)
    level = mathir_level(training)
    MACROS.write_text(macros(cells, level))
    print(json.dumps({'cells': len(cells), 'mathir_pmd_after': round(level['pmd'], 4),
                      'mathir_neff_after': round(level['neff'], 4),
                      'shift_range': [round(min(c['shift'] for c in cells), 4),
                                      round(max(c['shift'] for c in cells), 4)],
                      'macros': str(MACROS)}))


if __name__ == '__main__':
    main()
