#!/usr/bin/env python3
"""Emit the hosted PCMD table body: one row per level, five domain columns."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAYLOAD = ROOT / 'paper/results/mode_diversity_hosted.json'
OUT = ROOT / 'paper/results/mode_diversity_hosted_table_body.tex'
MACROS = ROOT / 'paper/results/mode_diversity_hosted_cohort_macros.tex'
SPARE_OUT = ROOT / 'paper/results/mode_diversity_hosted_nomathir_table_body.tex'
DOMAINS = ('graph_coloring', 'countdown', 'python_factors', 'mathir', 'pantry_plan')
# MathIR keys a mode by its derivation rather than its answer, and most of the
# derivations it certifies are longer routes no measured policy produces, so it
# sits near zero for every deployment for reasons that are partly the
# construction's. The cohort macro is reported with and without it.
DERIVATION_KEYED = 'mathir'


def fmt(value: float | None) -> str:
    if value is None:
        return '---'
    text = f'{value:.3f}'
    return text[1:] if text.startswith('0.') else text


def build(payload: dict) -> str:
    index = {(c['level'], c['domain']): c for c in payload['cells']}
    lines = []
    for level in (1, 2, 3):
        cells = [str(level)]
        for domain in DOMAINS:
            cell = index.get((level, domain))
            if cell is None or not cell['reportable']:
                cells.append('---')
            else:
                cells.append(f"{fmt(cell['pmd'])} ({cell['effective_modes']:.2f})")
        lines.append(' & '.join(cells) + r' \\')
    lines.append(r'    \bottomrule')
    return '\n'.join(lines) + '\n'


def _common_cells(payload: dict) -> set | None:
    """The (level, domain) pairs every deployment reports, as the payload lists them."""
    listed = payload.get('common_cells')
    if not listed:
        return None
    return {(entry['level'], entry['domain']) if isinstance(entry, dict)
            else (entry[0], entry[1]) for entry in listed}


def _macro_without(payload: dict, model: dict, domain: str) -> float | None:
    """The deployment's macro over the same common cells, minus one domain."""
    common = _common_cells(payload)
    values = [c['pmd'] for c in model['cells']
              if c['reportable'] and c['domain'] != domain
              and (common is None or (c['level'], c['domain']) in common)]
    return sum(values) / len(values) if values else None


def cohort_macros(payload: dict) -> str:
    """The two ceilings the manuscript's effective-mode sentence rests on.

    Emitted only while that sentence is still true of both: the five-domain
    macro stays under 1.5 effective modes and the MathIR-free macro under 1.6.
    If either crosses, the macros are withheld and the build fails on the
    sentence that quotes them rather than printing a bound it has outgrown.
    """
    full, spare = [], []
    for model in payload['models']:
        macro = model.get('macro_pmd_common_cells')
        if macro is not None and macro < 1:
            full.append(1 / (1 - macro))
        without = _macro_without(payload, model, DERIVATION_KEYED)
        if without is not None and without < 1:
            spare.append(1 / (1 - without))
    if not full or not spare or max(full) >= 1.5 or max(spare) >= 1.6:
        return ('% Generated by ops/build_mode_diversity_hosted_table.py; do not hand edit.\n'
                '% Effective-mode ceilings withheld: a deployment has crossed the bound the\n'
                '% manuscript states. Revisit the sentence that quotes these macros.\n')
    return ('% Generated by ops/build_mode_diversity_hosted_table.py; do not hand edit.\n'
            f'\\newcommand{{\\MDneffceiling}}{{{max(full):.2f}}}\n'
            f'\\newcommand{{\\MDneffceilingnomathir}}{{{max(spare):.2f}}}\n')


def build_cohort(payload: dict) -> str:
    """One row per deployment: macro PCMD, effective modes, and per-level macro."""
    # Ranked and reported on the comparable macro, not on each deployment's own
    # reportable cells: two deployments lose Python at Levels 2 and 3 to
    # provider refusals, and averaging each over whatever it can report ranked
    # them against a different, easier set of cells than the other five.
    lines = []
    key = lambda m: -(m.get('macro_pmd_common_cells') or -1)
    for model in sorted(payload['models'], key=key):
        macro = model.get('macro_pmd_common_cells')
        neff = 1.0 / (1.0 - macro) if macro is not None and macro < 1 else None
        cells = [model['label'], fmt(macro), f'{neff:.2f}' if neff else '---']
        for level in (1, 2, 3):
            level_cells = [c['pmd'] for c in model['cells']
                           if c['level'] == level and c['reportable']]
            cells.append(fmt(sum(level_cells) / len(level_cells)) if level_cells else '---')
        lines.append(' & '.join(cells) + r' \\')
    lines.append(r'    \bottomrule')
    return '\n'.join(lines) + '\n'


def build_without_mathir(payload: dict) -> str:
    """The same macro over the same common cells, minus the derivation-keyed domain.

    A separate body rather than two more columns on the cohort table: that table
    is bound by digest inside the hosted level-average record, and widening it
    invalidates a binding this comparison has no reason to touch.
    """
    lines = []
    key = lambda m: -(m.get('macro_pmd_common_cells') or -1)
    for model in sorted(payload['models'], key=key):
        spare = _macro_without(payload, model, DERIVATION_KEYED)
        neff = f'{1 / (1 - spare):.2f}' if spare is not None and spare < 1 else '---'
        lines.append(' & '.join([model['label'], fmt(spare), neff]) + r' \\')
    lines.append(r'    \bottomrule')
    return '\n'.join(lines) + '\n'


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--payload', type=Path, default=PAYLOAD)
    parser.add_argument('--output', type=Path, default=OUT)
    parser.add_argument('--cohort-payload', type=Path,
                        default=ROOT / 'paper/results/mode_diversity_hosted_cohort_20260917.json')
    parser.add_argument('--cohort-output', type=Path,
                        default=ROOT / 'paper/results/mode_diversity_hosted_cohort_table_body.tex')
    args = parser.parse_args()
    args.output.write_text(build(json.loads(args.payload.read_text())))
    cohort = json.loads(args.cohort_payload.read_text())
    args.cohort_output.write_text(build_cohort(cohort))
    SPARE_OUT.write_text(build_without_mathir(cohort))
    MACROS.write_text(cohort_macros(cohort))
    print(json.dumps({'event': 'built', 'output': str(args.output),
                      'cohort_output': str(args.cohort_output),
                      'macros': str(MACROS)}))


if __name__ == '__main__':
    main()
