#!/usr/bin/env python3
"""Does the concentration depend on what a domain calls a different mode?

ModeBench keys a mode three ways. In Countdown and MathIR two accepted outputs
differ when they reach the same answer by a different route; in Python when the
program behaves differently on the test inputs; in Graph and PantryPlan when
the answer itself differs. A reader can reasonably ask whether the reported
collapse is a property of reasoning at all, or only of the three domains whose
modes are outcomes.

That question is decidable from the concentration record already on disk. This
builder groups the frozen-to-terminal change in conditional collision by how
the domain keys a mode, so the effect can be read separately under each
definition rather than pooled across all five. Positive is concentration onto
fewer verified modes. RLVR-only arms only: the replay arms are the
intervention, not the phenomenon.
"""
from __future__ import annotations

import json
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "paper/results/conditional_concentration_20260914.json"
MACROS = ROOT / "paper/results/mode_keying_macros.tex"
OUT_JSON = ROOT / "paper/results/mode_keying_comparison.json"

# How each domain decides that two accepted outputs are different.
KEYING = {
    "countdown": "route", "mathir": "route",
    "python_factors": "behaviour",
    "graph_coloring": "answer", "pantry_plan": "answer",
}
LABEL = {"graph_coloring": "Graph", "countdown": "Countdown",
         "python_factors": "Python", "mathir": "MathIR", "pantry_plan": "Pantry"}
RLVR = {"drgrpo", "grpo", "maxrl"}


def main() -> int:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    by_keying: dict[str, list[float]] = defaultdict(list)
    by_domain: dict[str, list[float]] = defaultdict(list)
    for block in payload["blocks"]:
        if block.get("kind") != "before_after" or block.get("method") not in RLVR:
            continue
        summary = block["summaries"].get("distinct_streams") or {}
        for value in (summary.get("values") or {}).values():
            by_keying[KEYING[block["domain"]]].append(float(value))
            by_domain[block["domain"]].append(float(value))

    def stat(values):
        return {"n": len(values), "mean": statistics.fmean(values),
                "concentrated": sum(1 for v in values if v > 0)}

    record = {
        "generator": "ops/build_paper_mode_keying_comparison.py",
        "statistic": "change in conditional collision, frozen to terminal; "
                     "positive is concentration onto fewer verified modes",
        "arms": "RLVR-only (Dr.GRPO, GRPO, MaxRL)",
        "by_keying": {k: stat(v) for k, v in by_keying.items()},
        "by_domain": {k: stat(v) for k, v in by_domain.items()},
    }
    OUT_JSON.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n",
                        encoding="utf-8")

    # The cleanest route-keyed domain: same answer, different derivation, and
    # no structural gap between certified and producible modes.
    route = by_domain["countdown"]
    answer = by_keying["answer"]
    lines = ["% Generated by ops/build_paper_mode_keying_comparison.py; do not hand edit."]
    for name, values in (("Route", by_keying["route"]),
                         ("Answer", by_keying["answer"]),
                         ("Behaviour", by_keying["behaviour"])):
        s = stat(values)
        lines += [f"\\newcommand{{\\MDkey{name}N}}{{{s['n']}}}",
                  f"\\newcommand{{\\MDkey{name}Mean}}{{{s['mean']:+.3f}}}",
                  f"\\newcommand{{\\MDkey{name}Up}}{{{s['concentrated']}}}"]
    lines += [f"\\newcommand{{\\MDkeyCountdownMean}}{{{statistics.fmean(route):+.3f}}}",
              f"\\newcommand{{\\MDkeyCountdownN}}{{{len(route)}}}",
              f"\\newcommand{{\\MDkeyGraphMean}}"
              f"{{{statistics.fmean(by_domain['graph_coloring']):+.3f}}}",
              f"\\newcommand{{\\MDkeyMathIRMean}}"
              f"{{{statistics.fmean(by_domain['mathir']):+.3f}}}",
              f"\\newcommand{{\\MDkeyAnswerCells}}{{{len(answer)}}}"]
    MACROS.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {OUT_JSON.name}, {MACROS.name}\n")
    print(f"{'keying':<12}{'n':>5}{'mean dC':>10}{'concentrated':>14}")
    for k, v in sorted(by_keying.items()):
        s = stat(v)
        print(f"{k:<12}{s['n']:>5}{s['mean']:>+10.3f}"
              f"{s['concentrated']:>9}/{s['n']}")
    print()
    for k, v in sorted(by_domain.items()):
        s = stat(v)
        print(f"  {LABEL[k]:<12}({KEYING[k]:<9}) n={s['n']:<4} mean {s['mean']:+.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
