#!/usr/bin/env python3
"""Bind the paper's domain-prompt appendix to the frozen ModeBench splits.

The appendix in ``paper/main.tex`` reproduces, verbatim, the exact prompt the
policy receives in every reported domain: the dataset ``problem`` string of the
first row of that cohort's frozen evaluation split, wrapped by the same chat
template the launcher exported.  This script re-renders those prompts from the
datasets and fails closed when the typeset appendix has drifted from them.

Run ``--emit`` to print the LaTeX block instead of checking it.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import textwrap

ROOT = Path(os.environ.get("OAT_ZERO_REPO_ROOT", Path(__file__).resolve().parents[1]))
SRC = Path(os.environ.get("OAT_ZERO_SOURCE_ROOT", ROOT / "src"))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from oat_drgrpo.templates import TEMPLATE_FACTORY  # noqa: E402

PAPER = ROOT / "paper/main.tex"

# (label, latex title, data root, prompt template, launcher that exported it)
DOMAINS = (
    (
        "graph",
        "Graph coloring",
        "var/data/graph_coloring_modebench_v2",
        "qwen_boxed",
        "ops/exp_scaling/launch_e71_scale384_05b.sh",
    ),
    (
        "countdown",
        "Countdown",
        "var/data/exact_countdown_easy3_probe",
        "qwen_boxed",
        "ops/exp_scaling/launch_e70_clean_stage_a_05b.sh",
    ),
    (
        "python",
        "Python factors",
        "var/data/python_factor_modebench_v1",
        "qwen_boxed",
        "ops/exp_scaling/launch_e70_clean_stage_a_05b.sh",
    ),
    (
        "mathir",
        "MathIR action menu",
        "var/data/mathir_action_menu_v1",
        "qwen_boxed",
        "ops/exp_scaling/launch_e70_clean_stage_a_05b.sh",
    ),
    (
        "pantry",
        "PantryPlan",
        "var/data/pantry_plan_modebench_v2",
        "qwen_pantry_support_mask",
        "ops/exp_scaling/launch_e71_scale384_05b.sh",
    ),
)

BEGIN_MARKER = "% BEGIN generated by ops/check_paper_domain_prompts.py"
END_MARKER = "% END generated by ops/check_paper_domain_prompts.py"

# The vendored fancyvrb (v3.7) predates breaklines=true, so wrapping happens
# here.  Continuation lines carry a two-space indent and are recoverable: a
# wrapped logical line is exactly the continuation pieces rejoined by single
# spaces.  The round trip is asserted below, so no prompt character is lost.
WRAP_COLUMNS = 90
CONTINUATION_INDENT = "  "


def _wrap(line: str) -> list[str]:
    if len(line) <= WRAP_COLUMNS:
        return [line]
    pieces = textwrap.wrap(
        line,
        width=WRAP_COLUMNS,
        subsequent_indent=CONTINUATION_INDENT,
        break_long_words=False,
        break_on_hyphens=False,
        replace_whitespace=False,
        drop_whitespace=True,
    )
    rejoined = " ".join(
        piece[len(CONTINUATION_INDENT) :] if index else piece
        for index, piece in enumerate(pieces)
    )
    if rejoined != line:
        raise ValueError(f"prompt line is not recoverable after wrapping: {line!r}")
    return pieces


def _first_eval_prompt(root: Path, template: str) -> tuple[str, int, int]:
    from datasets import load_from_disk

    evaluation = load_from_disk(str(root / "eval"))
    split = next(iter(evaluation.keys()))
    train = load_from_disk(str(root / "train"))
    train_split = next(iter(train.keys()))
    problem = evaluation[split][0]["problem"]
    return (
        TEMPLATE_FACTORY[template](problem),
        len(train[train_split]),
        len(evaluation[split]),
    )


def render() -> str:
    lines: list[str] = [BEGIN_MARKER]
    for label, title, root, template, launcher in DOMAINS:
        rendered, train_rows, eval_rows = _first_eval_prompt(ROOT / root, template)
        if rendered.endswith("\n"):
            rendered = rendered[:-1]
        lines.append("")
        lines.append(f"\\subsection{{{title}}}")
        lines.append(f"\\label{{app:prompt-{label}}}")
        lines.append("")
        lines.append(
            f"\\noindent Template \\texttt{{{template.replace('_', chr(92) + '_')}}}; "
            f"{train_rows} training and {eval_rows} evaluation rows in "
            f"\\path{{{root}}}."
        )
        lines.append("")
        lines.append(
            "\\begin{Verbatim}[fontsize=\\scriptsize,frame=single,framesep=4pt,"
            "rulecolor=\\color{black!25}]"
        )
        for source_line in rendered.split("\n"):
            lines.extend(_wrap(source_line))
        lines.append("\\end{Verbatim}")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit",
        action="store_true",
        help="print the LaTeX block instead of checking the typeset appendix",
    )
    args = parser.parse_args()

    block = render()
    if args.emit:
        sys.stdout.write(block)
        return 0

    text = PAPER.read_text(encoding="utf-8")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        print(f"[prompts] missing generated block markers in {PAPER}", file=sys.stderr)
        return 1
    start = text.index(BEGIN_MARKER)
    end = text.index(END_MARKER) + len(END_MARKER) + 1
    typeset = text[start:end]
    if typeset != block:
        print(
            "[prompts] paper/main.tex domain prompts drifted from the frozen "
            "splits; regenerate with --emit",
            file=sys.stderr,
        )
        return 1
    print(f"[prompts] {len(DOMAINS)} domain prompts match the frozen splits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
