"""Bind the paper's domain-prompt appendix to the frozen ModeBench splits.

The appendix in ``paper/main.tex`` reproduces, verbatim, the exact prompt the
policy receives in every reported domain: the dataset ``problem`` string of the
first row of that cohort's frozen evaluation split, wrapped by the same chat
template the launcher exported.  This script re-renders those prompts from the
datasets and fails closed when the typeset appendix has drifted from them.

PantryPlan's surface is the six-bit support mask: the policy selects rows and a
trusted environment projects exact quantities onto them. Retained evaluation
draws store that projection rather than the policy's mask, so a regrade of a
saved PantryPlan response must not run the mask decode a second time.

Run ``--emit`` to print the LaTeX block instead of checking it.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import textwrap

ROOT = Path(os.environ.get("OAT_ZERO_REPO_ROOT", Path(__file__).resolve().parents[1]))
SRC = Path(os.environ.get("OAT_ZERO_SOURCE_ROOT", ROOT / "src"))
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from oat_drgrpo.templates import TEMPLATE_FACTORY  # noqa: E402

# The generated prompt block lives in the appendix, which main.tex pulls in
# with \input{appendix}. This script rewrites the block in place, so it
# must open the file the markers are actually in.
PAPER = ROOT / "paper/appendix.tex"

# (label, latex title, data root, prompt template, launcher that exported it)
DOMAINS = (
    (
        "graph",
        "Graph coloring",
        "var/data/graph_coloring_modebench_v2",
        "qwen_boxed",
        "ops/exp_scaling/launch_e71_scale384_05b.sh",
    ),
    (
        "countdown",
        "Countdown",
        "var/data/exact_countdown_easy3_probe",
        "qwen_boxed",
        "ops/exp_scaling/launch_e70_clean_stage_a_05b.sh",
    ),
    (
        "python",
        "Python factors",
        "var/data/python_factor_modebench_v1",
        "qwen_boxed",
        "ops/exp_scaling/launch_e70_clean_stage_a_05b.sh",
    ),
    (
        "mathir",
        "MathIR action menu",
        "var/data/mathir_action_menu_v1",
        "qwen_boxed",
        "ops/exp_scaling/launch_e70_clean_stage_a_05b.sh",
    ),
    (
        "pantry",
        "PantryPlan",
        "var/data/pantry_plan_modebench_v2",
        "qwen_pantry_support_mask",
        "ops/exp_scaling/launch_e71_scale384_05b.sh",
    ),
)

BEGIN_MARKER = "% BEGIN generated by ops/check_paper_domain_prompts.py"
END_MARKER = "% END generated by ops/check_paper_domain_prompts.py"

# The vendored fancyvrb (v3.7) predates breaklines=true, so wrapping happens
# here.  Continuation lines carry a two-space indent and are recoverable: a
# wrapped logical line is exactly the continuation pieces rejoined by single
# spaces.  The round trip is asserted below, so no prompt character is lost.
# 90 columns of \scriptsize typewriter plus the frame's 4pt separation and rule
# on each side overran the text block; 84 leaves the frame inside the measure.
WRAP_COLUMNS = 84
CONTINUATION_INDENT = "  "
#: A listing longer than this cannot share a page with its neighbour, so it is
#: allowed to break rather than strand the page above it.  Four of the five fit
#: well under it; PantryPlan's pantry table does not.
SAMEPAGE_MAX_LINES = 30


def _wrap(line: str) -> list[str]:
    if len(line) <= WRAP_COLUMNS:
        return [line]
    pieces = textwrap.wrap(
        line,
        width=WRAP_COLUMNS,
        subsequent_indent=CONTINUATION_INDENT,
        break_long_words=False,
        break_on_hyphens=False,
        replace_whitespace=False,
        drop_whitespace=True,
    )
    rejoined = " ".join(
        piece[len(CONTINUATION_INDENT) :] if index else piece
        for index, piece in enumerate(pieces)
    )
    if rejoined != line:
        raise ValueError(f"prompt line is not recoverable after wrapping: {line!r}")
    return pieces


def _first_eval_prompt(root: Path, template: str) -> tuple[str, int, int]:
    from datasets import load_from_disk

    evaluation = load_from_disk(str(root / "eval"))
    split = next(iter(evaluation.keys()))
    train = load_from_disk(str(root / "train"))
    train_split = next(iter(train.keys()))
    problem = evaluation[split][0]["problem"]
    return (
        TEMPLATE_FACTORY[template](problem),
        len(train[train_split]),
        len(evaluation[split]),
    )


def render() -> str:
    lines: list[str] = [BEGIN_MARKER]
    for label, title, root, template, launcher in DOMAINS:
        rendered, train_rows, eval_rows = _first_eval_prompt(ROOT / root, template)
        if rendered.endswith("\n"):
            rendered = rendered[:-1]
        lines.append("")
        # A prompt is one object: the heading names it, the line under the
        # heading says which split it came from, and the frame holds it.  Split
        # across a page boundary it reads as two fragments, so \filbreak moves
        # the whole group to the next page rather than breaking inside it.  There
        # is deliberately no closing \filbreak: its \vfil would make a break
        # right after the last frame free, stranding the rest of the page and
        # pushing App. D to a new one.  samepage already keeps that frame whole.
        wrapped = [piece for source_line in rendered.split("\n")
                   for piece in _wrap(source_line)]
        tall = len(wrapped) > SAMEPAGE_MAX_LINES
        # \filbreak is \vfil\penalty\vfilneg, so a break taken at it fills the
        # page above with infinite glue.  For a listing that cannot fit beside a
        # neighbour that empties the previous page, which is what stranded the
        # MathIR page.  A listing over the threshold is therefore left to flow
        # and to split, and only the short ones are kept whole.
        if not tall:
            lines.append("\\filbreak")
        lines.append(f"\\subsection{{{title}}}")
        lines.append(f"\\label{{app:prompt-{label}}}")
        lines.append("")
        lines.append(
            f"\\noindent {train_rows} training and {eval_rows} evaluation prompts."
        )
        lines.append("")
        # samepage keeps the frame itself whole even if \filbreak's group is
        # placed at a page bottom.  It is dropped for a listing too tall to
        # share a page with anything: PantryPlan's pantry table runs past thirty
        # lines, so \filbreak moved the whole block to a fresh page and left the
        # previous one three-quarters blank.  Letting that one frame break is
        # cheaper than the empty page, and the four short listings keep the
        # guarantee.  The threshold is the listing itself, not the domain name,
        # so a listing that grows past it is handled the same way.
        whole = "samepage=false" if tall else "samepage=true"
        lines.append(
            "\\begin{Verbatim}[fontsize=\\scriptsize,frame=single,framesep=4pt,"
            f"rulecolor=\\color{{black!25}},{whole}]"
        )
        lines.extend(wrapped)
        lines.append("\\end{Verbatim}")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit",
        action="store_true",
        help="print the LaTeX block instead of checking the typeset appendix",
    )
    args = parser.parse_args()

    block = render()
    if args.emit:
        sys.stdout.write(block)
        return 0

    text = PAPER.read_text(encoding="utf-8")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        print(f"[prompts] missing generated block markers in {PAPER}", file=sys.stderr)
        return 1
    start = text.index(BEGIN_MARKER)
    end = text.index(END_MARKER) + len(END_MARKER) + 1
    typeset = text[start:end]
    if typeset != block:
        print(
            "[prompts] paper/appendix.tex domain prompts drifted from the frozen "
            "splits; regenerate with --emit",
            file=sys.stderr,
        )
        return 1
    print(f"[prompts] {len(DOMAINS)} domain prompts match the frozen splits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
