#!/usr/bin/env python3
"""Native-HF frozen coding checkpoint evaluation with production sampler receipts.

Each invocation evaluates one declared shard. It creates no optimizer or replay
bank and never resumes training RNG. Samples are generated by the unchanged v2
trainer, with the global task index determining every batch seed.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import math
import os
from pathlib import Path
import time
from typing import Any, Mapping

import train_real_domains_pilot_20260921_v2 as trainer
import evaluate_real_domains_20260921 as metrics

SCHEMA = "native-hf-real-domains-evaluation-20260922-v1"
TRAINER_SHA256 = "e320611aa612d5f2772fe4b45f8e9bbbbad126a5666090b1f97f277049d00535"
MUTABLE_ADAPTER_KEYS = {"build_root", "runtime_root", "launcher", "scratch_root", "slate_root"}
SEED_RULE = "eval_seed + global_task_index * 10000 + batch_start_index"


def file_binding(path: str | Path, expected: str | None = None) -> dict:
    path = Path(path)
    actual = trainer.digest(path)
    if expected is not None and actual != expected:
        raise ValueError(f"file checksum drift: {path}")
    return {"path": str(path.resolve()), "sha256": actual}


def load_bound(path: str | Path, expected: str) -> Any:
    file_binding(path, expected)
    return json.loads(Path(path).read_text())


def semantic_training_config(config: Mapping[str, Any]) -> dict:
    resolved = trainer.resolve_config(config)
    resolved["adapter_config"] = {k: v for k, v in resolved["adapter_config"].items() if k not in MUTABLE_ADAPTER_KEYS}
    return resolved


def resolve_config(raw: Mapping[str, Any]) -> dict:
    config = dict(raw)
    if config.get("schema") != SCHEMA:
        raise ValueError("native HF evaluator schema required")
    training = trainer.resolve_config(config["training_config"])
    config["training_config"] = training
    if training["attention_implementation"] != "sdpa" or training["generation_batch_size"] != 4 or training["max_new_tokens"] != 1024 or training["seed"] != 88411:
        raise ValueError("fixed native coding sampler and initialization contract differs")
    if training["adapter_module"] != "build_constructive_code_hardened_20260921":
        raise ValueError("this evaluator is restricted to the hardened coding adapter")
    if config["arm"] not in {"base", "maxrl", "remax"}:
        raise ValueError("invalid evaluation arm")
    step = config["checkpoint_step"]
    if type(step) is not int or step < 0 or (config["arm"] == "base") != (step == 0):
        raise ValueError("checkpoint step and arm disagree")
    if bool(config.get("checkpoint_path")) != (config["arm"] != "base"):
        raise ValueError("checkpoint path required exactly for trained arms")
    order, selected = config["global_task_order"], config["task_ids"]
    if not order or len(order) != len(set(order)) or not selected or len(selected) != len(set(selected)) or not set(selected) <= set(order):
        raise ValueError("unique global and selected task IDs required")
    if selected != [task for task in order if task in set(selected)]:
        raise ValueError("shard must preserve global task order")
    cohorts = config["cohort_ids"]
    if set(cohorts) != {"train", "development"} or cohorts["train"] + cohorts["development"] != order or cohorts["train"] != training["train_ids"] or cohorts["development"] != training["eval_ids"]:
        raise ValueError("global order must be exact train then development IDs")
    counts = config["samples_per_task_by_id"]
    if set(counts) != set(selected) or any(type(n) is not int or not 4 <= n < 10000 or n % 4 for n in counts.values()):
        raise ValueError("exact per-task counts divisible by batch size four required")
    if config["eval_seed"] != 119411:
        raise ValueError("fixed evaluation RNG namespace differs")
    if not math.isfinite(config["max_gpu_hours"]) or not 0 < config["max_gpu_hours"] <= 4:
        raise ValueError("finite bounded GPU time required")
    if len(config["expected_initial_trainable_parameters_sha256"]) != 64:
        raise ValueError("expected initial LoRA hash required")
    if config.get("validation_only", False):
        if type(config["validation_only"]) is not bool or sum(counts.values()) > 32 or training["updates"] != 8 or step not in {0, 8}:
            raise ValueError("validation mode is restricted to corrected8 and at most32 draws")
    else:
        plan = load_bound(config["plan_path"], config["plan_sha256"])
        native = plan["native_hf_evaluation"]
        if order != native["global_task_order"] or cohorts["train"] != plan["dataset"]["train_ids"] or cohorts["development"] != plan["dataset"]["untrained_development_ids"]:
            raise ValueError("task cohort differs from fixed coding128 plan")
        if step not in {0, 32, 64, 128} or training["updates"] != 128 or config["training_provenance"]["terminal_updates"] != 128:
            raise ValueError("production evaluation requires the fixed128 trajectory")
        expected_train, expected_dev = (512, 128) if step in {0, 128} else (128, 32)
        if any(n != (expected_train if task in cohorts["train"] else expected_dev) for task, n in counts.items()):
            raise ValueError("sample counts differ from predeclared checkpoint budgets")
    return config


def validate_training_provenance(config: Mapping[str, Any]) -> dict:
    """Bind both original runs and allow sealed intermediate checkpoints only
    once their complete128 parent trajectory has finished successfully.
    """
    training = config["training_config"]
    provenance = config["training_provenance"]
    if set(provenance["runs"]) != {"maxrl", "remax"}:
        raise ValueError("both paired training identities required")
    if trainer.digest(Path(trainer.__file__)) != TRAINER_SHA256:
        raise ValueError("production sampler/trainer bytes differ from corrected version")
    records = {}
    for arm, paths in provenance["runs"].items():
        identity = load_bound(paths["identity_path"], paths["identity_sha256"])
        frozen = load_bound(paths["frozen_identity_path"], paths["frozen_identity_sha256"])
        if frozen.get("schema") != "real-domains-frozen-job-20260921-v1" or frozen["request"].get("arm") != arm or frozen["request"].get("entrypoint") != "train_real_domains_pilot_20260921_v2.py":
            raise ValueError("training frozen job arm or source contract differs")
        if identity.get("schema") != trainer.SCHEMA or identity.get("arm") != arm or identity["runner_sha256"] != TRAINER_SHA256 or identity["input_config_sha256"] != frozen["config_sha256"]:
            raise ValueError("training runtime identity differs from frozen job")
        if identity["config_sha256"] != trainer.identity(identity["config"]) or semantic_training_config(identity["config"]) != semantic_training_config(training):
            raise ValueError("training configuration differs from evaluation contract")
        if identity["model_config_sha256"] != trainer.digest(Path(training["model"]) / "config.json"):
            raise ValueError("base model configuration changed since training")
        if identity["initial_trainable_parameters_sha256"] != config["expected_initial_trainable_parameters_sha256"]:
            raise ValueError("paired initial LoRA hashes differ")
        by_snapshot = {row["snapshot"]: row["sha256"] for row in frozen["files"]}
        if len(by_snapshot) != len(frozen["files"]) or not any(path.endswith("/ops/train_real_domains_pilot_20260921_v2.py") and sha == TRAINER_SHA256 for path, sha in by_snapshot.items()):
            raise ValueError("corrected trainer bytes absent from frozen source identity")
        if by_snapshot.get(identity["adapter_module"]) != identity["adapter_module_sha256"]:
            raise ValueError("training adapter source absent from frozen identity")
        for name, expected in identity["production_source_sha256"].items():
            if not any(path.endswith("/src/" + name.replace(".", "/") + ".py") and sha == expected for path, sha in by_snapshot.items()):
                raise ValueError("production source absent from original frozen identity")
            if trainer.digest(Path(importlib.import_module(name).__file__)) != expected:
                raise ValueError("production learner/source bytes differ from training")
        result = None
        if paths.get("result_path"):
            result = load_bound(paths["result_path"], paths["result_sha256"])
            if result.get("schema") != trainer.SCHEMA or result.get("status") != "complete" or result.get("arm") != arm or result.get("completed_updates") != provenance["terminal_updates"] or result.get("config_sha256") != identity["config_sha256"]:
                raise ValueError("parent training trajectory did not complete as declared")
        elif config["arm"] != "base":
            raise ValueError("checkpoint evaluation requires both completed training runs")
        records[arm] = {"identity": identity, "result": result, "bindings": paths}
    if config["arm"] == "base":
        return {"runs": records, "checkpoint": None}
    checkpoint = Path(config["checkpoint_path"])
    arm, step = config["arm"], config["checkpoint_step"]
    identity = records[arm]["identity"]
    if step > provenance["terminal_updates"]:
        raise ValueError("checkpoint exceeds declared parent update count")
    seal = json.loads((checkpoint / "complete.json").read_text())
    if seal.get("schema") != trainer.SCHEMA or seal.get("arm") != arm or seal.get("completed_updates") != step or seal.get("config_sha256") != identity["config_sha256"]:
        raise ValueError("checkpoint seal differs from arm, step, or parent training")
    files = {"complete.json": trainer.digest(checkpoint / "complete.json")}
    for name, field in (("bank.json", "bank_sha256"), ("training.pt", "training_state_sha256")):
        files[name] = file_binding(checkpoint / name, seal[field])["sha256"]
    actual = {p.relative_to(checkpoint / "adapter").as_posix(): trainer.digest(p) for p in (checkpoint / "adapter").rglob("*") if p.is_file()}
    if actual != seal["adapter_files"]:
        raise ValueError("checkpoint adapter file set or contents differ from seal")
    files.update({"adapter/" + name: sha for name, sha in actual.items()})
    adapter = json.loads((checkpoint / "adapter" / "adapter_config.json").read_text())
    if Path(adapter["base_model_name_or_path"]).resolve() != Path(training["model"]).resolve() or adapter.get("r") != training["lora_rank"] or adapter.get("lora_alpha") != training["lora_alpha"] or set(adapter["target_modules"]) != set(training["lora_target_modules"]):
        raise ValueError("checkpoint LoRA architecture differs from initialization")
    return {"runs": records, "checkpoint": {"path": str(checkpoint), "seal": seal, "files_sha256": files}}


def validate_model_manifest(config: Mapping[str, Any]) -> dict:
    manifest = load_bound(config["model_manifest_path"], config["model_manifest_sha256"])
    root = Path(config["training_config"]["model"]).resolve()
    if manifest.get("schema") != "native-hf-model-files-20260922-v1" or Path(manifest["model_root"]).resolve() != root or manifest["model_revision"] != config["training_config"]["model_revision"]:
        raise ValueError("model manifest revision or root differs")
    expected = {}
    for row in manifest["files"]:
        relative = Path(row["relative_path"])
        if relative.is_absolute() or ".." in relative.parts or relative.as_posix() in expected or Path(row["path"]) != root / relative:
            raise ValueError("unsafe or duplicate model manifest path")
        expected[relative.as_posix()] = row["sha256"]
        if (root / relative).stat().st_size != row["size_bytes"]:
            raise ValueError("model file size differs")
        file_binding(root / relative, row["sha256"])
    actual = {p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file() and ".cache" not in p.relative_to(root).parts}
    if actual != set(expected) or not {"config.json", "tokenizer_config.json"} <= actual or not any(name.endswith(".safetensors") for name in actual):
        raise ValueError("model manifest does not bind the complete snapshot")
    return {"manifest_sha256": config["model_manifest_sha256"], "files": len(expected), "model_revision": manifest["model_revision"]}


def trainable_hash(model: Any) -> str:
    import torch
    return trainer.identity({name: hashlib.sha256(parameter.detach().cpu().contiguous().view(torch.uint8).numpy().tobytes()).hexdigest() for name, parameter in model.named_parameters() if parameter.requires_grad})


def make_model(config: Mapping[str, Any]) -> tuple[Any, dict]:
    """Construct the exact initial policy, then load the sealed default adapter.

    Loading tensors into the existing default adapter preserves FP32 LoRA and
    the exact module construction used by production, without optimizer/RNG IO.
    """
    import torch
    from transformers import AutoModelForCausalLM
    from peft import LoraConfig, get_peft_model, get_peft_model_state_dict, set_peft_model_state_dict
    from peft.utils.save_and_load import load_peft_weights
    training = config["training_config"]
    trainer.seed_all(training["seed"])
    model = AutoModelForCausalLM.from_pretrained(training["model"], local_files_only=True, torch_dtype=torch.bfloat16, attn_implementation="sdpa", device_map={"": 0})
    model = get_peft_model(model, LoraConfig(r=training["lora_rank"], lora_alpha=training["lora_alpha"], target_modules=training["lora_target_modules"], lora_dropout=0.0, bias="none", task_type="CAUSAL_LM"))
    model.config.use_cache = False
    model.enable_input_require_grads()
    model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
    for child in model.modules():
        if isinstance(child, torch.nn.Dropout):
            child.p = 0.0
    initial = trainable_hash(model)
    if initial != config["expected_initial_trainable_parameters_sha256"]:
        raise ValueError("native baseline initialization differs from paired training")
    if config["checkpoint_path"]:
        weights = load_peft_weights(str(Path(config["checkpoint_path"]) / "adapter"), device="cpu")
        loaded = set_peft_model_state_dict(model, weights, adapter_name="default")
        if loaded.unexpected_keys:
            raise ValueError("unexpected checkpoint adapter parameters")
        actual = get_peft_model_state_dict(model, adapter_name="default")
        if set(actual) != set(weights) or any(actual[name].dtype != weights[name].dtype or not torch.equal(actual[name].detach().cpu(), weights[name]) for name in weights):
            raise ValueError("loaded native adapter tensors differ from sealed weights")
    dtypes = sorted({str(parameter.dtype) for parameter in model.parameters() if parameter.requires_grad})
    base_dtypes = sorted({str(parameter.dtype) for parameter in model.parameters() if not parameter.requires_grad})
    if dtypes != ["torch.float32"] or base_dtypes != ["torch.bfloat16"]:
        raise ValueError("native model precision differs from BF16 base and FP32 LoRA")
    model.eval()
    return model, {"initial_trainable_parameters_sha256": initial, "loaded_trainable_parameters_sha256": trainable_hash(model), "adapter_dtypes": dtypes, "base_dtypes": base_dtypes, "trainable_parameters": sum(p.numel() for p in model.parameters() if p.requires_grad)}


def enrich_row(row: Mapping[str, Any], config: Mapping[str, Any], sampler: Mapping[str, Any]) -> dict:
    task_id = row["task_id"]
    index = config["global_task_order"].index(task_id)
    cohort = "train" if task_id in config["cohort_ids"]["train"] else "development"
    result = {**row, "arm": config["arm"], "checkpoint_step": config["checkpoint_step"], "cohort": cohort, "global_task_index": index, "batch_start_index": row["sample_index"] - row["batch_offset"], "request_seed": row["batch_seed"], "text_sha256": hashlib.sha256(row["text"].encode()).hexdigest(), "token_count": len(row["token_ids"]), "eos_token_ids": sampler["eos_token_ids"], "attention_mask": [1] * (len(row["prompt_token_ids"]) + len(row["token_ids"])), "loss_mask": [0] * (len(row["prompt_token_ids"]) - 1) + [1] * len(row["token_ids"])}
    if result["batch_seed"] != config["eval_seed"] + index * 10000 + result["batch_start_index"]:
        raise ValueError("generation seed differs from global shard-independent rule")
    return result


class ReceiptWriter:
    def __init__(self, handle: Any, config: Mapping[str, Any], sampler: Mapping[str, Any], deadline: float):
        self.handle, self.config, self.sampler, self.deadline = handle, config, sampler, deadline

    def write(self, line: str) -> int:
        if time.monotonic() >= self.deadline:
            raise TimeoutError("registered native evaluation GPU bound reached")
        return self.handle.write(json.dumps(enrich_row(json.loads(line), self.config, self.sampler), sort_keys=True, allow_nan=False) + "\n")

    def flush(self) -> None:
        self.handle.flush()

    def fileno(self) -> int:
        return self.handle.fileno()


def summarize_rows(task_rows: list[dict]) -> dict:
    if not task_rows:
        return {"tasks": 0, "samples": 0, "accepted": 0, "pcmd_eligible_tasks": 0, "macro_pcmd_over_eligible_tasks": None}
    eligible = [row["pcmd"] for row in task_rows if row["pcmd_eligible"]]
    common_k = set.intersection(*(set(row["pass_at_k"]) for row in task_rows))
    common_ed = set.intersection(*(set(row["expected_distinct_valid_modes_at_k"]) for row in task_rows))
    return {"tasks": len(task_rows), "samples": sum(row["samples"] for row in task_rows), "accepted": sum(row["accepted"] for row in task_rows), "macro_accuracy": sum(row["accuracy"] for row in task_rows) / len(task_rows), "pcmd_eligible_tasks": len(eligible), "pcmd_total_tasks": len(task_rows), "macro_pcmd_over_eligible_tasks": sum(eligible) / len(eligible) if eligible else None, "hard_violation_count": sum(row["hard_violation_count"] for row in task_rows), "macro_pass_at_k": {k: sum(row["pass_at_k"][k] for row in task_rows) / len(task_rows) for k in sorted(common_k, key=int)}, "macro_expected_distinct_valid_modes_at_k": {k: sum(row["expected_distinct_valid_modes_at_k"][k] for row in task_rows) / len(task_rows) for k in sorted(common_ed, key=int)}}


def run(config_path: Path, output: Path, preflight: bool = False) -> dict:
    started = time.monotonic()
    config = resolve_config(json.loads(config_path.read_text()))
    paths = {key: output.with_name(output.stem + "." + key + suffix) for key, suffix in (("responses", ".jsonl"), ("attempts", ".jsonl"), ("progress", ".json"))}
    if output.exists() or any(path.exists() for path in paths.values()):
        raise FileExistsError("native evaluation output must be new")
    output.parent.mkdir(parents=True, exist_ok=True)
    training = config["training_config"]
    provenance = validate_training_provenance(config)
    model_manifest = validate_model_manifest(config)
    module = importlib.import_module(training["adapter_module"])
    tasks = module.load_tasks(training["adapter_config"])
    task_map = {task.task_id: task for task in tasks}
    if len(task_map) != len(tasks) or not set(config["global_task_order"]) <= set(task_map):
        raise ValueError("adapter task map is incomplete or duplicated")
    dataset = module.dataset_identity(training["adapter_config"])
    for record in provenance["runs"].values():
        original = record["identity"]
        if trainer.digest(Path(module.__file__)) != original["adapter_module_sha256"] or {k: v for k, v in dataset.items() if k != "selected_problem_ids"} != {k: v for k, v in original["dataset_identity"].items() if k != "selected_problem_ids"}:
            raise ValueError("native evaluator source/data differ from training")
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(training["model"], local_files_only=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id
    prompts = {task_id: tokenizer.encode(task_map[task_id].prompt, add_special_tokens=False) for task_id in config["global_task_order"]}
    if any(not ids or len(ids) + training["max_new_tokens"] > training["max_context_tokens"] for ids in prompts.values()):
        raise ValueError("native evaluation forbids prompt truncation")
    identity = {"schema": SCHEMA, "config": config, "config_sha256": trainer.identity(config), "input_config_sha256": trainer.digest(config_path), "runner_sha256": trainer.digest(Path(__file__)), "trainer_sha256": trainer.digest(Path(trainer.__file__)), "metrics_helper_sha256": trainer.digest(Path(metrics.__file__)), "adapter_module_sha256": trainer.digest(Path(module.__file__)), "dataset_identity": dataset, "model_manifest": model_manifest, "training_provenance": provenance, "model_config_sha256": trainer.digest(Path(training["model"]) / "config.json"), "tasks": [{"task_id": task_id, "global_task_index": config["global_task_order"].index(task_id), "family": task_map[task_id].family, "split": task_map[task_id].split, "prompt_sha256": hashlib.sha256(task_map[task_id].prompt.encode()).hexdigest(), "prompt_token_ids": prompts[task_id]} for task_id in config["global_task_order"]]}
    if preflight:
        result = {"schema": SCHEMA, "status": "preflight_pass", "identity": identity}
        metrics.atomic_json(output, result)
        return result
    import torch
    if not torch.cuda.is_available() or torch.cuda.device_count() != 1 or not torch.cuda.is_bf16_supported():
        raise RuntimeError("exactly one BF16-capable allocated CUDA GPU required")
    model, model_receipt = make_model(config)
    eos = model.generation_config.eos_token_id or tokenizer.eos_token_id
    eos_ids = sorted(eos if isinstance(eos, (tuple, list)) else [eos])
    if not eos_ids or any(type(x) is not int for x in eos_ids):
        raise ValueError("finite integer EOS set required")
    sampler = {"backend": "transformers/PEFT", "attention_implementation": "sdpa", "generation_batch_size": 4, "temperature": 1.0, "top_k": 0, "top_p": 1.0, "do_sample": True, "num_beams": 1, "repetition_penalty": 1.0, "generation_use_cache": True, "model_config_use_cache": False, "max_new_tokens": 1024, "prompt_truncation": False, "eos_token_ids": eos_ids, "pad_token_id": tokenizer.pad_token_id, "bos_token_id": tokenizer.bos_token_id, "tokenizer_length": len(tokenizer), "model_vocab_size": int(model.config.vocab_size), "tokenizer_vocab_upper": min(len(tokenizer), int(model.config.vocab_size)), "seed_rule": SEED_RULE, "eval_seed": config["eval_seed"], "raw_generated_eos_retained": True, "post_eos_padding_removed": True, "attention_mask": "ones over exact prompt+response; no persisted padding", "loss_mask": "causally shifted; zero over prompt targets and one over every response token including EOS"}
    import peft, transformers
    identity.update({"model": model_receipt, "sampler": sampler, "torch_version": torch.__version__, "peft_version": peft.__version__, "transformers_version": transformers.__version__, "gpu": torch.cuda.get_device_name()})
    deadline = started + config["max_gpu_hours"] * 3600
    rows = []
    try:
        with paths["responses"].open("x") as candidates, paths["attempts"].open("x") as verified:
            writer = ReceiptWriter(candidates, config, sampler, deadline)
            for task_id in config["task_ids"]:
                task = task_map[task_id]
                index = config["global_task_order"].index(task_id)
                cohort = "train" if task_id in config["cohort_ids"]["train"] else "development"
                phase = f"native_hf:{config['arm']}:{cohort}"
                samples, timing = trainer.generate_samples(model, tokenizer, task, prompts[task_id], config["samples_per_task_by_id"][task_id], training, phase, config["checkpoint_step"], writer, seed_base=config["eval_seed"] + index * 10000)
                enriched = [{**enrich_row(row, config, sampler), **row["verdict"]} for row in samples]
                trainer.append_rows(verified, enriched)
                summary = metrics.mode_metrics([row["verdict"] for row in samples])
                rows.append({"task_id": task_id, "family": task.family, "split": task.split, "cohort": cohort, "global_task_index": index, **summary, "timing": timing})
                metrics.atomic_json(paths["progress"], {"status": "running", "identity": identity, "completed_task_ids": [row["task_id"] for row in rows], "completed_samples": sum(row["samples"] for row in rows), "task_results": rows, "seconds": time.monotonic() - started})
                print(f"native HF {config['arm']} step{config['checkpoint_step']} {task_id}: {summary['accepted']}/{summary['samples']}, {summary['distinct_valid_modes']} modes", flush=True)
        if trainable_hash(model) != model_receipt["loaded_trainable_parameters_sha256"]:
            raise ValueError("evaluation mutated adapter parameters")
        if provenance["checkpoint"]:
            checkpoint = provenance["checkpoint"]
            for relative, expected in checkpoint["files_sha256"].items():
                file_binding(Path(checkpoint["path"]) / relative, expected)
        result = {"schema": SCHEMA, "status": "complete", "validation_only": config.get("validation_only", False), "identity": identity, "task_results": rows, "summary": summarize_rows(rows), "cohort_summaries": {cohort: summarize_rows([row for row in rows if row["cohort"] == cohort]) for cohort in ("train", "development")}, "artifacts": {key: file_binding(paths[key]) for key in ("responses", "attempts")}, "evaluation_bank_mutations": 0, "evaluation_optimizer_steps": 0, "adapter_hash_unchanged": True, "seconds": time.monotonic() - started, "allocated_gpu_hours_during_runner": (time.monotonic() - started) / 3600}
        metrics.atomic_json(output, result)
        metrics.atomic_json(paths["progress"], {"status": "complete", "output": str(output), "output_sha256": trainer.digest(output)})
        return result
    except BaseException as exc:
        metrics.atomic_json(paths["progress"], {"status": "failed", "identity": identity, "task_results": rows, "seconds": time.monotonic() - started, "error": f"{type(exc).__name__}: {exc}"})
        raise


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--preflight", action="store_true")
    args = parser.parse_args()
    result = run(args.config, args.output, args.preflight)
    print(json.dumps({"status": result["status"], "output": str(args.output)}, sort_keys=True))


if __name__ == "__main__":
    main()
