#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/ops/repo_env.sh"

CANONICAL_PYTHON_BIN="${ROOT_DIR}/var/seed_paper_eval/paper310/bin/python"
PYTHON_BIN="${OAT_ZERO_PYTHON:-$CANONICAL_PYTHON_BIN}"

export RUN_STAMP="${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}"

TINY_MODEL="${OAT_ZERO_TINY_MODEL:-qwen2.5-0.5b-instruct}"
case "$TINY_MODEL" in
  qwen2.5-0.5b-instruct|qwen25-0.5b-instruct|qwen-0.5b)
    DEFAULT_PRETRAIN="Qwen/Qwen2.5-0.5B-Instruct"
    DEFAULT_PROMPT_TEMPLATE="qwen_math"
    MODEL_TAG="qwen25_0p5b_instruct"
    ;;
  smollm2-135m|smollm2-135m-instruct|smol-135m)
    DEFAULT_PRETRAIN="HuggingFaceTB/SmolLM2-135M-Instruct"
    DEFAULT_PROMPT_TEMPLATE="no"
    MODEL_TAG="smollm2_135m_instruct"
    ;;
  custom)
    if [[ -z "${OAT_ZERO_PRETRAIN:-}" ]]; then
      echo "OAT_ZERO_TINY_MODEL=custom requires OAT_ZERO_PRETRAIN" >&2
      exit 1
    fi
    DEFAULT_PRETRAIN="$OAT_ZERO_PRETRAIN"
    DEFAULT_PROMPT_TEMPLATE="${OAT_ZERO_PROMPT_TEMPLATE:-no}"
    MODEL_TAG="$(printf '%s' "$DEFAULT_PRETRAIN" | tr '/:@' '___' | tr -cd 'A-Za-z0-9_.-')"
    ;;
  *)
    echo "Unknown OAT_ZERO_TINY_MODEL=${TINY_MODEL}" >&2
    echo "Use qwen2.5-0.5b-instruct, smollm2-135m, or custom." >&2
    exit 1
    ;;
esac

VARIANT="${OAT_ZERO_TINY_VARIANT:-current_drx}"
case "$VARIANT" in
  grpo)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-grpo}"
    export OAT_ZERO_POLICY_ENTROPY_COEF="${OAT_ZERO_POLICY_ENTROPY_COEF:-0.0}"
    VARIANT_TAG="grpo"
    ;;
  grpo_entropy)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-grpo}"
    export OAT_ZERO_POLICY_ENTROPY_COEF="${OAT_ZERO_POLICY_ENTROPY_COEF:-0.01}"
    VARIANT_TAG="grpo_entropy"
    ;;
  xdr)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-grpo}"
    export OAT_ZERO_POLICY_ENTROPY_COEF="${OAT_ZERO_POLICY_ENTROPY_COEF:-0.0}"
    export OAT_ZERO_XDR_TAU="${OAT_ZERO_XDR_TAU:-0.25}"
    VARIANT_TAG="xdr"
    ;;
  seed)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-grpo}"
    export OAT_ZERO_POLICY_ENTROPY_COEF="${OAT_ZERO_POLICY_ENTROPY_COEF:-0.0}"
    export OAT_ZERO_SEED_ENTROPY_ALPHA="${OAT_ZERO_SEED_ENTROPY_ALPHA:-1.0}"
    VARIANT_TAG="seed"
    ;;
  current_drx)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.10}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-anchor_rare}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-utility_centered}"
    VARIANT_TAG="current_drx"
    ;;
  drx_aux)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.10}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.05}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-anchor_rare}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-utility_centered}"
    VARIANT_TAG="drx_aux"
    ;;
  drx_aux_conservative)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.10}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.003}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_GROUP_FILTER="${OAT_ZERO_MAXENT_SEQUENCE_AUX_GROUP_FILTER:-mixed}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_MAX_EXPECTED_LEN_DROP="${OAT_ZERO_MAXENT_SEQUENCE_AUX_MAX_EXPECTED_LEN_DROP:-8}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_MAX_EXPECTED_LEN_GAIN="${OAT_ZERO_MAXENT_SEQUENCE_AUX_MAX_EXPECTED_LEN_GAIN:-8}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_MAX_EXPECTED_FORMAT_DROP="${OAT_ZERO_MAXENT_SEQUENCE_AUX_MAX_EXPECTED_FORMAT_DROP:-0.0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_MIN_EXPECTED_CORRECTNESS_DELTA="${OAT_ZERO_MAXENT_SEQUENCE_AUX_MIN_EXPECTED_CORRECTNESS_DELTA:-0.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-anchor_rare}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-utility_centered}"
    VARIANT_TAG="drx_aux_conservative"
    ;;
  drx_weighted)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.10}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-anchor_rare}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-weighted}"
    VARIANT_TAG="drx_weighted"
    ;;
  drx_maxent_centered)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.0}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_CANDIDATE_KL_COEF="${OAT_ZERO_MAXENT_CANDIDATE_KL_COEF:-0.0}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-competitive}"
    export OAT_ZERO_MAXENT_COMPETITIVE_MODE_BUDGET_MAX="${OAT_ZERO_MAXENT_COMPETITIVE_MODE_BUDGET_MAX:-0.0}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_EARLY="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_EARLY:-0.0}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_LATE="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_LATE:-0.0}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-maxent_centered}"
    VARIANT_TAG="drx_maxent_centered"
    ;;
  drx_correct_cluster)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.0}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_CANDIDATE_KL_COEF="${OAT_ZERO_MAXENT_CANDIDATE_KL_COEF:-0.0}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-correctness_conditioned}"
    export OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_ANSWER_LEVEL="${OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_ANSWER_LEVEL:-1}"
    export OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_MIN_ANSWER_COUNT="${OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_MIN_ANSWER_COUNT:-2}"
    export OAT_ZERO_MAXENT_COMPETITIVE_MODE_BUDGET_MAX="${OAT_ZERO_MAXENT_COMPETITIVE_MODE_BUDGET_MAX:-0.10}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_EARLY="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_EARLY:-0.10}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_LATE="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_LATE:-0.10}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-maxent_centered}"
    VARIANT_TAG="drx_correct_cluster"
    ;;
  answer_maxent)
    export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
    export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
    export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.0}"
    export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
    export OAT_ZERO_MAXENT_CANDIDATE_KL_COEF="${OAT_ZERO_MAXENT_CANDIDATE_KL_COEF:-0.0}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
    export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
    export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
    export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_CLUSTER_METHOD="${OAT_ZERO_MAXENT_SEMANTIC_CLUSTER_METHOD:-answer_family}"
    export OAT_ZERO_MAXENT_SEMANTIC_EMBEDDING_SIMILARITY_THRESHOLD="${OAT_ZERO_MAXENT_SEMANTIC_EMBEDDING_SIMILARITY_THRESHOLD:-2.0}"
    export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-correctness_conditioned}"
    export OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_ANSWER_LEVEL="${OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_ANSWER_LEVEL:-1}"
    export OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_MIN_ANSWER_COUNT="${OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_MIN_ANSWER_COUNT:-2}"
    export OAT_ZERO_MAXENT_COMPETITIVE_MODE_BUDGET_MAX="${OAT_ZERO_MAXENT_COMPETITIVE_MODE_BUDGET_MAX:-0.20}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_ENABLED="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_ENABLED:-0}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_EARLY="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_EARLY:-0.20}"
    export OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_LATE="${OAT_ZERO_MAXENT_CORRECTNESS_SCHEDULE_BUDGET_MAX_LATE:-0.20}"
    export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-maxent_centered}"
    VARIANT_TAG="answer_maxent"
    ;;
  *)
    echo "Unknown OAT_ZERO_TINY_VARIANT=${VARIANT}" >&2
    echo "Use grpo, grpo_entropy, xdr, seed, current_drx, drx_aux, drx_aux_conservative, drx_weighted, drx_maxent_centered, drx_correct_cluster, or answer_maxent." >&2
    exit 1
    ;;
esac

DATA_ROOT="${OAT_ZERO_TINY_DATA_ROOT:-$ROOT_DIR/var/data/exact_countdown_easy3_probe}"
if [[ ! -f "$DATA_ROOT/train/dataset_dict.json" ]] || [[ ! -f "$DATA_ROOT/eval/dataset_dict.json" ]]; then
  if [[ ! -x "$PYTHON_BIN" ]]; then
    echo "Missing OAT python at $PYTHON_BIN" >&2
    exit 1
  fi
  "$PYTHON_BIN" "$ROOT_DIR/ops/make_exact_countdown_mode_data.py" \
    --output-root "$DATA_ROOT" \
    --train-size "${OAT_ZERO_COUNTDOWN_MODE_TRAIN_SIZE:-384}" \
    --eval-size "${OAT_ZERO_COUNTDOWN_MODE_EVAL_SIZE:-128}" \
    --number-count "${OAT_ZERO_COUNTDOWN_MODE_NUMBER_COUNT:-3}" \
    --max-value "${OAT_ZERO_COUNTDOWN_MODE_MAX_VALUE:-12}" \
    --multi-min-modes "${OAT_ZERO_COUNTDOWN_MODE_MULTI_MIN_MODES:-2}" \
    --multi-max-modes "${OAT_ZERO_COUNTDOWN_MODE_MULTI_MAX_MODES:-8}" \
    --seed "${OAT_ZERO_COUNTDOWN_MODE_DATA_SEED:-0}" \
    --overwrite
fi

NUM_SAMPLES_FOR_TOPOLOGY="${OAT_ZERO_NUM_SAMPLES:-8}"
TOPOLOGY="${OAT_ZERO_TINY_TOPOLOGY:-single_gpu}"
case "$TOPOLOGY" in
  single_gpu)
    export OAT_ZERO_N_GPU="${OAT_ZERO_N_GPU:-1}"
    export OAT_ZERO_TRAIN_BATCH_SIZE="${OAT_ZERO_TRAIN_BATCH_SIZE:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    export OAT_ZERO_TRAIN_BATCH_SIZE_PER_DEVICE="${OAT_ZERO_TRAIN_BATCH_SIZE_PER_DEVICE:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    export OAT_ZERO_ROLLOUT_BATCH_SIZE="${OAT_ZERO_ROLLOUT_BATCH_SIZE:-1}"
    export OAT_ZERO_ROLLOUT_BATCH_SIZE_PER_DEVICE="${OAT_ZERO_ROLLOUT_BATCH_SIZE_PER_DEVICE:-1}"
    export OAT_ZERO_PI_BUFFER_MAXLEN_PER_DEVICE="${OAT_ZERO_PI_BUFFER_MAXLEN_PER_DEVICE:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    ;;
  row_sharded)
    export OAT_ZERO_NUM_SAMPLES="$NUM_SAMPLES_FOR_TOPOLOGY"
    export OAT_ZERO_N_GPU="${OAT_ZERO_N_GPU:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    export OAT_ZERO_TRAIN_BATCH_SIZE="${OAT_ZERO_TRAIN_BATCH_SIZE:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    export OAT_ZERO_TRAIN_BATCH_SIZE_PER_DEVICE="${OAT_ZERO_TRAIN_BATCH_SIZE_PER_DEVICE:-1}"
    export OAT_ZERO_ROLLOUT_BATCH_SIZE="${OAT_ZERO_ROLLOUT_BATCH_SIZE:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    export OAT_ZERO_ROLLOUT_BATCH_SIZE_PER_DEVICE="${OAT_ZERO_ROLLOUT_BATCH_SIZE_PER_DEVICE:-1}"
    export OAT_ZERO_PI_BUFFER_MAXLEN_PER_DEVICE="${OAT_ZERO_PI_BUFFER_MAXLEN_PER_DEVICE:-$NUM_SAMPLES_FOR_TOPOLOGY}"
    ;;
  *)
    echo "Unknown OAT_ZERO_TINY_TOPOLOGY=${TOPOLOGY}" >&2
    echo "Use single_gpu or row_sharded." >&2
    exit 1
    ;;
esac

export OAT_ZERO_PYTHON="$PYTHON_BIN"
export OAT_ZERO_SOURCE_ROOT="${OAT_ZERO_SOURCE_ROOT:-$ROOT_DIR/src}"
export OAT_ZERO_PRETRAIN="${OAT_ZERO_PRETRAIN:-$DEFAULT_PRETRAIN}"
export OAT_ZERO_PROMPT_TEMPLATE="${OAT_ZERO_PROMPT_TEMPLATE:-$DEFAULT_PROMPT_TEMPLATE}"
export OAT_ZERO_PROMPT_DATA="${OAT_ZERO_PROMPT_DATA:-$DATA_ROOT/train}"
export OAT_ZERO_EVAL_DATA="${OAT_ZERO_EVAL_DATA:-$DATA_ROOT/eval}"
export OAT_ZERO_TEST_SPLIT="${OAT_ZERO_TEST_SPLIT:-all}"
export OAT_ZERO_NUM_SAMPLES="${OAT_ZERO_NUM_SAMPLES:-$NUM_SAMPLES_FOR_TOPOLOGY}"
export OAT_ZERO_MAX_TRAIN="${OAT_ZERO_MAX_TRAIN:-64}"
export OAT_ZERO_NUM_PROMPT_EPOCH="${OAT_ZERO_NUM_PROMPT_EPOCH:-2}"
export OAT_ZERO_LEARNING_RATE="${OAT_ZERO_LEARNING_RATE:-0.000005}"
export OAT_ZERO_EVAL_STEPS="${OAT_ZERO_EVAL_STEPS:-4}"
export OAT_ZERO_SAVE_STEPS="${OAT_ZERO_SAVE_STEPS:-$OAT_ZERO_EVAL_STEPS}"
export OAT_ZERO_SAVE_FROM="${OAT_ZERO_SAVE_FROM:-0}"
export OAT_ZERO_SAVE_CKPT="${OAT_ZERO_SAVE_CKPT:-1}"
export OAT_ZERO_SAVE_INITIAL_MODEL="${OAT_ZERO_SAVE_INITIAL_MODEL:-1}"
if [[ "$OAT_ZERO_SAVE_CKPT" == "0" ]]; then
  export OAT_ZERO_REQUIRE_FULL_EVAL_CHECKPOINTS="${OAT_ZERO_REQUIRE_FULL_EVAL_CHECKPOINTS:-0}"
fi
export OAT_ZERO_MAX_SAVE_NUM="${OAT_ZERO_MAX_SAVE_NUM:-8}"
export OAT_ZERO_MAX_SAVE_MEM="${OAT_ZERO_MAX_SAVE_MEM:-2000}"
export OAT_ZERO_PROMPT_MAX_LENGTH="${OAT_ZERO_PROMPT_MAX_LENGTH:-256}"
export OAT_ZERO_GENERATE_MAX_LENGTH="${OAT_ZERO_GENERATE_MAX_LENGTH:-256}"
export OAT_ZERO_EVAL_BATCH_SIZE="${OAT_ZERO_EVAL_BATCH_SIZE:-32}"
export OAT_ZERO_EVAL_GENERATE_MAX_LENGTH="${OAT_ZERO_EVAL_GENERATE_MAX_LENGTH:-256}"
export OAT_ZERO_EVAL_MODE_COVERAGE_K="${OAT_ZERO_EVAL_MODE_COVERAGE_K:-0}"
export OAT_ZERO_EVAL_MODE_COVERAGE_TEMPERATURE="${OAT_ZERO_EVAL_MODE_COVERAGE_TEMPERATURE:-1.0}"
export OAT_ZERO_TEMPERATURE="${OAT_ZERO_TEMPERATURE:-1}"
export OAT_ZERO_TOP_P="${OAT_ZERO_TOP_P:-1}"
export OAT_ZERO_EVAL_TEMPERATURE="${OAT_ZERO_EVAL_TEMPERATURE:-0}"
export OAT_ZERO_ENABLE_FLASH_ATTN="${OAT_ZERO_ENABLE_FLASH_ATTN:-0}"
export OAT_ZERO_VLLM_GPU_RATIO="${OAT_ZERO_VLLM_GPU_RATIO:-0.25}"
export OAT_ZERO_USE_WB="${OAT_ZERO_USE_WB:-0}"
export OAT_ZERO_WB_PROJECT="${OAT_ZERO_WB_PROJECT:-oat-zero-tiny}"
export OAT_ZERO_WB_RUN_NAME="${OAT_ZERO_WB_RUN_NAME:-tiny-${MODEL_TAG}-${VARIANT_TAG}-${TOPOLOGY}-${RUN_STAMP}}"
export SAVE_PATH="${SAVE_PATH:-$ROOT_DIR/var/data/oat_zero_tiny_${MODEL_TAG}_${VARIANT_TAG}_${TOPOLOGY}_${RUN_STAMP}}"

echo "[tiny-probe] model=${OAT_ZERO_PRETRAIN}"
echo "[tiny-probe] prompt_template=${OAT_ZERO_PROMPT_TEMPLATE}"
echo "[tiny-probe] variant=${VARIANT_TAG}"
echo "[tiny-probe] topology=${TOPOLOGY}"
echo "[tiny-probe] data_root=${DATA_ROOT}"
echo "[tiny-probe] save_path=${SAVE_PATH}"

exec "$ROOT_DIR/ops/run_oat_zero_exact_1p5b_upstream.sh" "$@"
