#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export RUN_STAMP="${RUN_STAMP:-$(date +%Y%m%d_%H%M%S)}"
export SAVE_PATH="${SAVE_PATH:-$ROOT_DIR/var/data/oat_zero_exact_drx_1p5b_${RUN_STAMP}}"
export OAT_ZERO_WB_PROJECT="${OAT_ZERO_WB_PROJECT:-oat-zero}"
export OAT_ZERO_WB_RUN_NAME="${OAT_ZERO_WB_RUN_NAME:-qwen2.5-Math-1.5b-r1-zero-readmeflash-exact-drx-outputmaxent-lam010-seqaux005-${RUN_STAMP}}"
export OAT_ZERO_EVAL_STEPS="${OAT_ZERO_EVAL_STEPS:-16}"
export OAT_ZERO_SAVE_STEPS="${OAT_ZERO_SAVE_STEPS:-${OAT_ZERO_EVAL_STEPS}}"
export OAT_ZERO_SAVE_FROM="${OAT_ZERO_SAVE_FROM:-0}"
export OAT_ZERO_SAVE_CKPT="${OAT_ZERO_SAVE_CKPT:-1}"
export OAT_ZERO_SAVE_INITIAL_MODEL="${OAT_ZERO_SAVE_INITIAL_MODEL:-1}"
export OAT_ZERO_MAX_SAVE_NUM="${OAT_ZERO_MAX_SAVE_NUM:-999999}"
export OAT_ZERO_MAX_SAVE_MEM="${OAT_ZERO_MAX_SAVE_MEM:-99999999}"

# Reuse the exact README-flash runtime, but force the learner onto the exact
# listwise / DrX objective while keeping the row-sharded batch-1 update shape.
export OAT_ZERO_OBJECTIVE="${OAT_ZERO_OBJECTIVE:-maxent_listwise}"
export OAT_ZERO_BETA="${OAT_ZERO_BETA:-0}"
export OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA="${OAT_ZERO_SEMANTIC_ENTROPY_LAMBDA:-0.10}"
export OAT_ZERO_IGNORE_NO_EOS="${OAT_ZERO_IGNORE_NO_EOS:-0}"
export OAT_ZERO_MAXENT_TAU="${OAT_ZERO_MAXENT_TAU:-0.25}"
export OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_PRIMARY:-1}"
export OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE="${OAT_ZERO_MAXENT_EXACT_DRX_WEIGHT_SOURCE:-sequence_clipped}"
export OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE="${OAT_ZERO_MAXENT_USE_CLIP_OBJECTIVE:-0}"
export OAT_ZERO_MAXENT_CLIP_MODE="${OAT_ZERO_MAXENT_CLIP_MODE:-sequence}"
export OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF="${OAT_ZERO_MAXENT_SEQUENCE_AUX_COEF:-0.05}"
export OAT_ZERO_MAXENT_NEUTRAL_PROJECTION_COEF="${OAT_ZERO_MAXENT_NEUTRAL_PROJECTION_COEF:-0.0}"
export OAT_ZERO_MAXENT_SEMANTIC_SIMILARITY_THRESHOLD="${OAT_ZERO_MAXENT_SEMANTIC_SIMILARITY_THRESHOLD:-0.75}"
export OAT_ZERO_MAXENT_SEMANTIC_EMBEDDING_SIMILARITY_THRESHOLD="${OAT_ZERO_MAXENT_SEMANTIC_EMBEDDING_SIMILARITY_THRESHOLD:-0.9}"
export OAT_ZERO_MAXENT_SEMANTIC_CLUSTER_METHOD="${OAT_ZERO_MAXENT_SEMANTIC_CLUSTER_METHOD:-default}"
export OAT_ZERO_MAXENT_SEMANTIC_EMBEDDING_MAX_TOKENS="${OAT_ZERO_MAXENT_SEMANTIC_EMBEDDING_MAX_TOKENS:-512}"
export OAT_ZERO_MAXENT_SEMANTIC_CLUSTER_MAX_TOKENS="${OAT_ZERO_MAXENT_SEMANTIC_CLUSTER_MAX_TOKENS:-450}"
export OAT_ZERO_MAXENT_SEMANTIC_SPECTRAL_MAX_CLUSTERS="${OAT_ZERO_MAXENT_SEMANTIC_SPECTRAL_MAX_CLUSTERS:-0}"
export OAT_ZERO_MAXENT_SEMANTIC_SPECTRAL_EIGENGAP_MIN="${OAT_ZERO_MAXENT_SEMANTIC_SPECTRAL_EIGENGAP_MIN:-0.05}"
export OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_TARGET_FRAC="${OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_TARGET_FRAC:-0.5}"
export OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_SHARPNESS="${OAT_ZERO_MAXENT_SEMANTIC_CORRECTNESS_SHARPNESS:-4.0}"
export OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE="${OAT_ZERO_MAXENT_SEMANTIC_REMIX_MODE:-anchor_rare}"
export OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_ADVANTAGE_SOURCE:-utility_centered}"
export OAT_ZERO_MAXENT_DRGRPO_TOKEN_LENGTH_NORMALIZER="${OAT_ZERO_MAXENT_DRGRPO_TOKEN_LENGTH_NORMALIZER:-max_length}"
export OAT_ZERO_MAXENT_LENGTH_NORMALIZE_REF="${OAT_ZERO_MAXENT_LENGTH_NORMALIZE_REF:-1}"
export OAT_ZERO_MAXENT_LENGTH_NORMALIZE_POLICY="${OAT_ZERO_MAXENT_LENGTH_NORMALIZE_POLICY:-1}"

export OAT_ZERO_NUM_SAMPLES="${OAT_ZERO_NUM_SAMPLES:-8}"
export OAT_ZERO_TRAIN_BATCH_SIZE="${OAT_ZERO_TRAIN_BATCH_SIZE:-128}"
export OAT_ZERO_TRAIN_BATCH_SIZE_PER_DEVICE="${OAT_ZERO_TRAIN_BATCH_SIZE_PER_DEVICE:-1}"
export OAT_ZERO_ROLLOUT_BATCH_SIZE="${OAT_ZERO_ROLLOUT_BATCH_SIZE:-128}"
export OAT_ZERO_ROLLOUT_BATCH_SIZE_PER_DEVICE="${OAT_ZERO_ROLLOUT_BATCH_SIZE_PER_DEVICE:-16}"
export OAT_ZERO_PI_BUFFER_MAXLEN_PER_DEVICE="${OAT_ZERO_PI_BUFFER_MAXLEN_PER_DEVICE:-128}"

# Keep the runtime close to the batch-1 README comparisons unless a caller
# explicitly overrides the actor / learner memory split.
export OAT_ZERO_VLLM_GPU_RATIO="${OAT_ZERO_VLLM_GPU_RATIO:-0.35}"
export OAT_ZERO_MAX_NORM="${OAT_ZERO_MAX_NORM:-1.0}"

if [[ -z "${PYTORCH_CUDA_ALLOC_CONF:-}" ]] || [[ "${PYTORCH_CUDA_ALLOC_CONF:-}" == *"expandable_segments:"* ]]; then
  export PYTORCH_CUDA_ALLOC_CONF="max_split_size_mb:128"
fi

exec "$ROOT_DIR/ops/run_oat_zero_exact_1p5b_upstream.sh" "$@"
