#!/usr/bin/env python3
"""Numerical illustration of KL and replay recovery in a categorical flow.

The appendix proves Theta(1/[s log(1/s)]) KL recovery and
Theta(log(1/s)) replay recovery on a specified two-correct-mode face.
This script integrates a separate seven-category system with finite initial
logits and a uniform reference. Its finite-depth results illustrate the
contrast; they do not certify the two-mode asymptotic constants for this
larger system. The other depleted logits start at -40.

Integration uses RK4 in logit space with a step capped by the velocity.
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / "paper/results/kl_replay_recovery_flow.json"
MACROS = ROOT / "paper/results/kl_replay_recovery_macros.tex"
TABLE = ROOT / "paper/results/kl_replay_recovery_table_body.tex"

M_CORRECT = 4          # correct modes the prompt admits
N_INCORRECT = 3        # incorrect categories
GROUP = 16             # G, the fresh rollout group size
C_G = (GROUP - 1) / GROUP          # the Dr.GRPO coefficient
TARGET = 0.05          # the probability a recovered mode must reach
DEPTHS = (1e-3, 1e-4, 1e-5, 1e-6)
BETAS = (0.04, 0.1)
RHOS = (0.01, 0.1)
CRUSHED_LOGIT = -40.0  # the other categories, at collapse


def softmax(z: list[float]) -> list[float]:
    top = max(z)
    exp = [math.exp(value - top) for value in z]
    total = sum(exp)
    return [value / total for value in exp]


def velocity(z, beta, mu, rho, w):
    p = softmax(z)
    correct = sum(p[a] for a in range(M_CORRECT))
    out = [C_G * p[a] * ((1.0 if a < M_CORRECT else 0.0) - correct)
           for a in range(len(z))]
    if beta:
        divergence = sum(p[a] * math.log(p[a] / mu[a]) for a in range(len(z)))
        for a in range(len(z)):
            out[a] += beta * p[a] * (math.log(mu[a] / p[a]) + divergence)
    if rho:
        for a in range(len(z)):
            out[a] -= rho * (p[a] - w[a])
    return out


def recovery_time(depth, *, beta=0.0, mu=None, rho=0.0, w=None,
                  tolerance=1e-3, max_steps=4_000_000):
    """Time for the depleted correct mode to reach TARGET, or None."""
    size = M_CORRECT + N_INCORRECT
    z = [CRUSHED_LOGIT] * size
    z[1] = 0.0                      # the mode that won
    z[0] = math.log(depth)          # the mode to recover
    time = 0.0
    for _ in range(max_steps):
        v = velocity(z, beta, mu, rho, w)
        span = max(abs(value) for value in v)
        step = min(1e7, tolerance / max(span, 1e-300))
        k1 = v
        k2 = velocity([z[i] + .5 * step * k1[i] for i in range(size)], beta, mu, rho, w)
        k3 = velocity([z[i] + .5 * step * k2[i] for i in range(size)], beta, mu, rho, w)
        k4 = velocity([z[i] + step * k3[i] for i in range(size)], beta, mu, rho, w)
        z = [z[i] + step * (k1[i] + 2 * k2[i] + 2 * k3[i] + k4[i]) / 6
             for i in range(size)]
        time += step
        if softmax(z)[0] >= TARGET:
            return time
    return None



def emit_paper(curves, summary) -> None:
    """Macros and the table body the appendix inputs; never hand edited."""
    ratios = [r for values in summary["kl_multiplicative_per_decade"].values()
              for r in values]
    MACROS.write_text(
        "% Generated by ops/verify_kl_replay_recovery_flow.py; do not hand edit.\n"
        f"\\newcommand{{\\MDklModes}}{{{M_CORRECT}}}\n"
        f"\\newcommand{{\\MDklTarget}}{{{TARGET:.2f}}}\n"
        f"\\newcommand{{\\MDklDecadeKL}}{{{min(ratios):.1f}--{max(ratios):.1f}}}\n",
        encoding="utf-8",
    )
    order = ([f"kl_beta_{beta}" for beta in BETAS]
             + [f"replay_rho_{rho}" for rho in RHOS])
    label = {f"kl_beta_{beta}": f"Reference KL, $\\beta={beta}$" for beta in BETAS}
    label.update({f"replay_rho_{rho}": f"Verified replay, $\\rho={rho}$"
                  for rho in RHOS})
    lines = []
    for name in order:
        cells = "  &  ".join(
            f"{curves[name][f'{depth:.0e}']:.2e}" for depth in DEPTHS
        )
        lines.append(f"  {label[name]}  &  {cells} \\\\")
    TABLE.write_text(
        "% Generated by ops/verify_kl_replay_recovery_flow.py; do not hand edit.\n"
        + "\n".join(lines)
        + "\n  \\bottomrule\n",
        encoding="utf-8",
    )


def main() -> int:
    size = M_CORRECT + N_INCORRECT
    mu = [1.0 / size] * size
    w = [1.0 / M_CORRECT if a < M_CORRECT else 0.0 for a in range(size)]

    curves: dict[str, dict[str, float | None]] = {}
    for beta in BETAS:
        curves[f"kl_beta_{beta}"] = {
            f"{depth:.0e}": recovery_time(depth, beta=beta, mu=mu)
            for depth in DEPTHS
        }
    for rho in RHOS:
        curves[f"replay_rho_{rho}"] = {
            f"{depth:.0e}": recovery_time(depth, rho=rho, w=w)
            for depth in DEPTHS
        }

    def per_decade(name, multiplicative):
        times = [curves[name][f"{depth:.0e}"] for depth in DEPTHS]
        if any(value is None for value in times):
            raise SystemExit(f"{name}: a depth never recovered")
        if multiplicative:
            return [later / earlier for earlier, later in zip(times, times[1:])]
        return [later - earlier for earlier, later in zip(times, times[1:])]

    summary = {
        "kl_multiplicative_per_decade": {
            name: per_decade(name, True) for name in curves if name.startswith("kl_")
        },
        "replay_additive_per_decade": {
            name: per_decade(name, False)
            for name in curves if name.startswith("replay_")
        },
        # Two-mode asymptotic reference value; this larger system is illustrative.
        "replay_predicted_additive_per_decade": {
            f"replay_rho_{rho}": math.log(10.0) / rho for rho in RHOS
        },
    }

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(
        json.dumps(
            {
                "generator": "ops/verify_kl_replay_recovery_flow.py",
                "correct_modes": M_CORRECT,
                "incorrect_categories": N_INCORRECT,
                "group_size": GROUP,
                "target_probability": TARGET,
                "depths": list(DEPTHS),
                "reference": "uniform",
                "recovery_times": curves,
                "summary": summary,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    emit_paper(curves, summary)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"wrote {MACROS.relative_to(ROOT)} and {TABLE.relative_to(ROOT)}")
    for name, values in curves.items():
        rendered = "  ".join(f"{k}:{v:.3e}" for k, v in values.items())
        print(f"  {name:<18} {rendered}")
    for name, ratios in summary["kl_multiplicative_per_decade"].items():
        print(f"  {name} x/decade: {[round(r, 2) for r in ratios]}")
    for name, gaps in summary["replay_additive_per_decade"].items():
        predicted = summary["replay_predicted_additive_per_decade"][name]
        print(f"  {name} +/decade: {[round(g, 1) for g in gaps]} "
              f"(predicted {predicted:.1f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
