compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
mixed_precision: bf16
num_machines: 1
num_processes: 7
machine_rank: 0
same_network: true
rdzv_backend: static
tpu_use_cluster: false
tpu_use_sudo: false
tpu_env: []
use_cpu: false
downcast_bf16: 'no'
main_training_function: main
